### ISSUE TITLE
Zero width emotes not showing correctly. 

### ISSUE THREAD

**Issue by Immac** [steveseguin/social_stream#104]
What is happening?

- Zero width emotes are shown to the side of other emotes

What should happen?

- Zero width emotes should show on top of other emotes
(Note the _rain_ emote, on 7tv)
![image](https://user-images.githubusercontent.com/3265190/236499069-8d39b8ad-af97-4bba-9912-f82bb88bda51.png)

**Comment by steveseguin** [comment]
Is this specific to 7tv emotes only?

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/236586783-b83d4a6c-d58c-4f8f-a6f8-a28576a852da.png)
fixed for twitch + 7tv
