### ISSUE TITLE
Odysee Not Working

### ISSUE THREAD

**Issue by filcard** [steveseguin/social_stream#108]
Odysee.com has stopped working for me since about a week ago. With the Odysee pop-out chat window open, Social Stream no longer picks up on posted chat messages. Using latest Chrome browser and Social Stream browser extension. All 5 other platforms I restream to still work like a charm. I'm guessing Odysee launched an update that breaks the expected location of things.

**Comment by steveseguin** [comment]
Hi. Thank you for reporting the issue.

can you re-download/update the social stream extension, then refresh the chat pop out, and let me know if its working again?

![image](https://github.com/steveseguin/social_stream/assets/2575698/03008a16-de39-487e-a735-f52ae962adc3)

**Comment by filcard** [comment]
Will do. Currently occupied over the holiday, but I'll try it soon. Thanks! Happy Memorial Day

**Comment by filcard** [comment]
Yep, works great again! Thanks for the fix. 🎉🎊🥳
