### ISSUE TITLE
Social Media version not updating

### ISSUE THREAD

**Issue by j2chulo** [steveseguin/social_stream#110]
I was running social media version  1.50.15 and today I downloaded the new version 1.54.2 after replacing social_stream_main directoy with the newest files my browser still say I have 1.50.15 installed. I did removed from my google chrome extension first them re-add it. I even try to  add it from a new directory but same issues still saying I have 1.50.15 any help?

**Comment by steveseguin** [comment]
While just replacing the old files with new ones, then reloading, should be enough, you can make sure the extension is fully removed:
![image](https://github.com/steveseguin/social_stream/assets/2575698/1bbf7df0-9361-4094-b310-38f32a9da815)

Once the extension isn't found anywhere anymore, and any old folder you removed / deleted, try downloading the new version here:

https://github.com/steveseguin/social_stream/archive/refs/heads/main.zip

Extra this zip to a folder.

Inside the folder, the file called package.json should have the version number in it. It should be 1.54.2 -- if its not that version, then its not the right folder or you unzipped the wrong file.  Rename the folder with the version name so you can easily identify it.

From Chrome, load the unpacked extension, selecting the folder with the version name that's correct.
