### ISSUE TITLE
Display YouTube Comments (not live chat)

### ISSUE THREAD

**Issue by maxwo007** [steveseguin/social_stream#111]
Would it be possible to integrate YouTube comments under the videos (i.e. not the live chat)?

**Comment by maxwo007** [comment]
Thanks for your time and effort you put into the project and this reply here.

The idea is not to show live comments, but to comment on existing comments under YouTube videos in the livestream. To do this, I encourage my viewers to write comments under my YouTube video, which I then respond to live in the stream some time later.

Comments should preferably be individually selectable. This way, users can decide for themselves which comments they want to respond to.

Replies to comments would then probably also be counted as a single comment. If you want to show the entire conversation in the stream, you simply go through answer by answer. This way you can also skip unwanted replies if necessary.

Now in my case I was looking for a tool to not have to take screenshots of comments to show them in the stream.
At first sight I thought that social_stream would be my solution. Therefore, I had wondered with the abundance of supported platforms, why standard youtube comments are not there yet.

Thank you very much :-)

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/a9edd679-5ab9-48cb-88aa-80672ca0c21e)
![image](https://github.com/steveseguin/social_stream/assets/2575698/d1249bab-0040-4db2-9180-b26fbdcf4aae)

Added.  Press SS, then select the comment you wish to push to the dock in socialstream. You can have the dock auto-publish to the highlight page, if you dont want to re-select the messages there as well.

**Comment by maxwo007** [comment]
Fantastic. thank you very much!
