### ISSUE TITLE
Youtube Chat URL changes

### ISSUE THREAD

**Issue by bensam123** [steveseguin/social_stream#112]
Not sure if this is a issue or I'm doing it wrong, but every time I go live on Youtube it changes the chat URL so you need to repopout the chat compared to Kick or Twitch, which always have a static chat URL. Is it possible to always have the right window popped out?

**Comment by steveseguin** [comment]
I think if you use the option to quick-pop out the chat in the extension, it will auto-find the current proper Youtube window to pop out.  You can have this configured so it auto-opens when the dock opens, and it should also mostly prevent duplicate windows from popping out
![image](https://github.com/steveseguin/social_stream/assets/2575698/e87f9c4d-be45-4ffb-b121-a5c138a2e285)

**Comment by bensam123** [comment]
Hey Steve, doesn't look like this works. FB opens just the profile page and Youtube doesn't seem to do anything. Kick works, but that has a permanent chat. Youtube has a channel ID, perhaps that could be used to figure it out? Everything works when the windows are open, but loading each window every time you start streaming is a process.
