### ISSUE TITLE
7tv Emotes + Kick.com

### ISSUE THREAD

**Issue by bloodsinc** [steveseguin/social_stream#116]
Hello, the best ever multichat is super good, thx for it, my emotes from 7tv working for twitch , for youtube, for trovo, but not working for kick, idk why, all the extensions and settings are set, but only for kick 7tv not working and u can see only text, any solutions ? Im use the opera

**Comment by bloodsinc** [comment]
> Thank you. I think the issue is probably that I just haven't added 7TV support to kick yet; didn't even know 7TV supported kick, but I can try to find time to fix that.

BIGBIG thx, your chat is the best chat ever i've seen for a while, im just restreaming on a 4+ platforms and its the best ) another thx for fix

**Comment by steveseguin** [comment]
I added support for 7tv.  I don't support SVG images, but I think everyone else works, including zero-width emotes.

update and re-open if issues persist.

**Comment by bloodsinc** [comment]
Thx all working properly
