### ISSUE TITLE
Last update, twitch chat dont working at all

### ISSUE THREAD

**Issue by bloodsinc** [steveseguin/social_stream#117]
hello , today updating the ninja chat for last version and my twitch chat dont working at all, all others chats like trovo kick and youtube working like intended, and i cant download the past version with Tw chat working, thx in advance for FIX

**Comment by bloodsinc** [comment]
> Thank you for reporting the issue - I think my 7TV support for Twitch broke -- I'll take a look and fix

Thx bro, u are awesome

**Comment by steveseguin** [comment]
I think it's fixed; needs an update tho. thank you

**Comment by bloodsinc** [comment]
> I think it's fixed; needs an update tho. thank you

all's working now, THX
