### ISSUE TITLE
Zero Width emotes and Emote Wall

### ISSUE THREAD

**Issue by Immac** [steveseguin/social_stream#118]
Zero Width emotes get separated from the emotes they are supposed to cover in the emotes wall.
![image](https://github.com/steveseguin/social_stream/assets/3265190/9779f7d4-5671-4ab0-9587-00472b4d5c62)

**Comment by steveseguin** [comment]
thank you. I'll fix.  Emotes wall.. forgot to add it there also.

**Comment by steveseguin** [comment]
I pushed an update.  It will go live in the next little while, once the cache clears and refreshes.
