### ISSUE TITLE
Alternating Chat Background Switching

### ISSUE THREAD

**Issue by chrisspiegl** [steveseguin/social_stream#12]
I noticed that when the dock is open the background of the chat messages can start to alternate back and forth and not stay the same for each message for the duration it is on screen.

This is kind of irritating and makes it visually hard to read the messages before bringing them live in a high chat volume stream.

Example:

![78A9092D-F97E-41DE-B477-DF8347C6CFA8-17923-000059B4F5E3F55E](https://user-images.githubusercontent.com/1096384/166890394-d9132fa3-6851-4043-8b29-c6fa9c92db05.gif)

Cheers,
Chris

**Comment by chrisspiegl** [comment]
Workaround right now is to disable the alternating background shadow via adding `&hideshadow` to the chat control url.

**Comment by steveseguin** [comment]
Thank you for pointing that out.  Will fix

**Comment by steveseguin** [comment]
I think I fixed this. thank you

**Comment by chrisspiegl** [comment]
Tested, seems to be fixed. Thank you.
