### ISSUE TITLE
New Integration Request

### ISSUE THREAD

**Issue by Kiet-Kat** [steveseguin/social_stream#123]
Hi Steve!

I know you probably have a huge backlog of items to work on but I was wondering if it would be possible to add chat integration with Vstream, it's pretty new but could be useful to some. 

Site is here: [vstream.com](https://vstream.com/)
Here's a url to a sample pop out chat that they have https://vstream.com/v/DGIRlowBToytJaDV58SRjw/chat-popout

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/343298af-a485-413b-9330-d1021af04734)

Added.  Sorry for the delay.

**Comment by steveseguin** [comment]
I updated it to support avatars, colored names, and fixed an issue with it breaking with recent vstream ui changes.

![image](https://github.com/steveseguin/social_stream/assets/2575698/63e046dd-0025-4fef-9117-e3c0a623e183)
