### ISSUE TITLE
New Social Red to add

### ISSUE THREAD

**Issue by Grafimia** [steveseguin/social_stream#126]
There is a new social network under development in Spain that I would like to be able to use with Social Stream.

https://estrim.com

Now they are in the entry phase, so you need an invitation code, use mine without problems for whatever you need.
Code: TECNOPOLIT

Thanks A lot

**Comment by steveseguin** [comment]
Thank you for the request.

I tried signing up to explore the site, but it's asking for my telephone number, and at the moment I'm not too keen to share that personal information with a social network.  I'll try again later, perhaps with a temporary number.

Anyways, I'm not sure if this site has live video chat, live chat, or just static posted messages.  Is there a rush to have this supported?  Is it still being developed and changing a lot?

If you wanted to take a stab adding it yourself, I have a video guide on how to do that here: https://www.youtube.com/watch?v=5LquQ1xhmms

**Comment by Grafimia** [comment]
Hello Steve,Thanks for your help. Yes this social network have Live video chat, I have you access with this user and password. It's a test account. User: CuriosityPass: 12345678Thanks for your help Un Saludo

Javier BenitezEl 15 ago. 2023, a las 21:24, Steve Seguin ***@***.***> escribieron:Thank you for the request.I tried signing up to explore the site, but it's asking for my telephone number, and at the moment I'm not too keen to share that personal information with a social network.  I'll try again later, perhaps with a temporary number.Anyways, I'm not sure if this site has live video chat, live chat, or just static posted messages.  Is there a rush to have this supported?  Is it still being developed and changing a lot?If you wanted to take a stab adding it yourself, I have a video guide on how to do that here: https://www.youtube.com/watch?v=5LquQ1xhmms—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by steveseguin** [comment]
Thank you

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/e81d6e6d-bef5-4f74-bd88-9c4d0fecf87b)
Added.

If you have issues with it, re-open the ticket. thank you
