### ISSUE TITLE
Disable TikTok Follow, Like, Share Chat Messages

### ISSUE THREAD

**Issue by RealProHenis** [steveseguin/social_stream#127]
Is there a way I can disable the chat from showing the TikTok follower, like, share, etc messages in chat?

**Comment by steveseguin** [comment]
You should be able to get rid of them if you disable the 'Capture stream events"

You can hide specific events as well, by listing keywords to match -- events that contain a keyword listed will be blocked.

You can also try the 'stream events fade up' option, to make them less annoying. (relatively new, so  be sure to be up to date)

![image](https://github.com/steveseguin/social_stream/assets/2575698/1df16d40-2ca7-4284-bdc4-75ff59f58d38)
![image](https://github.com/steveseguin/social_stream/assets/2575698/13f5eb64-199c-4f18-9c77-1144bb16190b)

**Comment by RealProHenis** [comment]
That's great, thanks! 

Now if I uncheck the "Capture stream events and actions", does that mean that YouTube superchats and Twitch bits won't be shown in chat?

**Comment by steveseguin** [comment]
I don't consider a donation as a stream event.
