### ISSUE TITLE
Position the Highlighted Message to be at the bottom

### ISSUE THREAD

**Issue by chrisspiegl** [steveseguin/social_stream#13]
I found it better for the layout to have the chat message align with the bottom when it is shorter and grow toward the top when the text is longer instead of having all messages kind of show up a set position from the bottom.

To do so, I had to make the `#message` set to `position: relative` which I think it also could be by default since it has no absolute positioning.

```css
#output {
    position: absolute;
    bottom: 50px;
}

#message {
    position: relative;
}
```

It's great that this is possible via CSS and can be easily adjusted. But I thought I'd put it here to either include it as a setting or for people trying to figure this out to have a solution ready.

**Example Before:**

<img width="529" alt="Capture 2022-05-05 at 11 04 07" src="https://user-images.githubusercontent.com/1096384/166893089-f6ab3c6b-f62a-4aa4-8c48-00e68cdb1b86.png">

**Example After:**

<img width="529" alt="Capture 2022-05-05 at 11 03 48" src="https://user-images.githubusercontent.com/1096384/166893083-75d8d9a7-7fbd-4075-98f6-9b44a483d6da.png">

**Comment by diegoveloper** [comment]
awesome! any plan to merge this on the `main` branch?

**Comment by steveseguin** [comment]
I've added it now; should be live in a few minutes.

Thank you to both of you.  Adding it slipped my mind as I wanted to test it a bit first, but it seems to work fine as I test it now.

https://github.com/steveseguin/social_stream/commit/8df6b4768db808f4195e81f717acab0f275a5e56

![image](https://user-images.githubusercontent.com/2575698/177087115-426a750b-6135-4ad7-afa9-5d50be394690.png)

**Comment by chrisspiegl** [comment]
In my experience, the best trick is to just make it as big as the stream window you are producing (usually 1920x1080).

The chat box will from what I remember have a `max-height` so it should be limited in that way anyways. 

But this way you never run the risk of a message being chopped off (as long as it fits into 1920x1080).
