### ISSUE TITLE
Restream Chat not working

### ISSUE THREAD

**Issue by JAMED051** [steveseguin/social_stream#132]
I've tried using Restream chat the past few streams, but it isn't send the data to OBS Studio.

**Comment by steveseguin** [comment]
On first glance here it seems to be working, but maybe there's some custom settings in restream that I'm not supporting?

Does the data appear in the dock?  Do "test" messages or any other site work?

I open: https://chat.restream.io/chat to use

![image](https://github.com/steveseguin/social_stream/assets/2575698/20f819f1-2656-4b05-be72-6c27b6cec610)


Did you customize the appearance at all in restream? if so, that might help me debug the issue

![image](https://github.com/steveseguin/social_stream/assets/2575698/c596dec9-c58f-49eb-9b19-4cc4add068f3)

**Comment by JAMED051** [comment]
Hey Steve!

Thank you for the quick reply! I just checked all the boxes in Appearance
and it now works with the link you sent me! However, I was to use the
plugin for scheduled events in Restream as well. Since it generates a
different URL, is there a place I can plug the unique URL?

For example, this will be the URL I use for tonight's stream:
https://chat.restream.io/embed?token=c66f79e7-7dd2-4ddf-82db-fad0f6aadbb4

Thank you again for your help!
Dillon James

**Comment by steveseguin** [comment]
I pushed a change that might help make it work, but otherwise I might need to join the live chat once its active to fix things for sure. I'm not really sure how you generated that embed link and it wont let me send messages as a test right now.

**Comment by JAMED051** [comment]
Sounds good! The link was generated by Restream when I scheduled the event. The stream will be live at 9pm ET, so I'll try it and see if it works. 

Here's the link to the stream, if you want to stop in and see if it's working: https://www.youtube.com/live/6wh5_TuRQ2E?si=vvSAa8dOXUIFMlQO

**Comment by steveseguin** [comment]
just noting that you'd need to update the extension to get the change:

It's a one-line change really
https://github.com/steveseguin/social_stream/commit/c6232bef224307c7d89caa09685808a543a753e1

**Comment by JAMED051** [comment]
Just updated it, thank you!

**Comment by JAMED051** [comment]
Hey Steve!

Restream Chat isn't working after the latest update. :/
