### ISSUE TITLE
 Manifest file is missing or unreadable

### ISSUE THREAD

**Issue by PAC23pacman** [steveseguin/social_stream#137]
Hi,
Being using social stream chat on my win7 pc and chrome smoothly, but a couple of months ago it stopped working.
Trying to reinstall chorme extention it prompts an error 
**"Manifest file is missing or unreadable"**

Is there a way to get this working again on my pc?
thanks
![2023-09-29_10h20_43](https://github.com/steveseguin/social_stream/assets/145875405/821ad2ea-4b74-410f-b7c6-6e41d82ad926)

**Comment by steveseguin** [comment]
Can you confirm you selected the right folder?
https://youtu.be/Zql6Q5H2Eqw?t=84

If you did, can you let me know which version of Chrome you are using?

**Comment by PAC23pacman** [comment]
> Can you confirm you selected the right folder? https://youtu.be/Zql6Q5H2Eqw?t=84
> 
> If you did, can you let me know which version of Chrome you are using?

Thanks Steve.
Now the error is gone. I will update this post once I confirm the plugin is working. 
Really thanks!

**Comment by PAC23pacman** [comment]
> Can you confirm you selected the right folder? https://youtu.be/Zql6Q5H2Eqw?t=84
> 
> If you did, can you let me know which version of Chrome you are using?

Ok, Ive followed your video steps, but the page where the facebook chat should replicate the comments is empty. Tried different live videos with same results. I dont remember having this issue first time I use this plugin. Am I missing something?

My system is win7 and my chrome version is **Version 109.0.5414.120 (Official Build) (64-bit)**
![2023-09-29_10h46_25](https://github.com/steveseguin/social_stream/assets/145875405/1f870108-da34-4bff-b7c2-7d14129fa8a3)

**Comment by PAC23pacman** [comment]
> Can you confirm you selected the right folder? https://youtu.be/Zql6Q5H2Eqw?t=84
> 
> If you did, can you let me know which version of Chrome you are using?

Yes, my mistake. I was not selecting the right folder. But now Im not getting comments on dock file. I will close this issue and open a new one, thanks.
