### ISSUE TITLE
Linkedin able to push but not pulling comments

### ISSUE THREAD

**Issue by Dputz** [steveseguin/social_stream#145]
I am struggling with being able to pull in the comments from linkedin either from the Live producer screen or the event video screen.  I am able to send broadcasted messages to it.

**Comment by steveseguin** [comment]
Do you have a live stream I can test with that's available?

I can't host linkedin events myself, so I need to find others or have others host

**Comment by Dputz** [comment]
Yes. How would be the best way to connect on one?

**Comment by steveseguin** [comment]
The "best" way is to probably text chat with me on Discord (https://discord.vdo.ninja) , but I'm open to other options.

**Comment by Dputz** [comment]
Sent an email
