### ISSUE TITLE
Filter for Donation / Super Chats

### ISSUE THREAD

**Issue by chrisspiegl** [steveseguin/social_stream#15]
I think it'd be a great idea to add a way to filter between paid / donated chat messages and things like that to focus on those?

Spotting the super chats in a lot of other chat messages can be a bit hard (even though they are already kind of highlighted right now).

I would say this would be a great button at the top in the menu next to the filter text field to toggle between "Donation Messages" and "Regular Chat" (which should include the donation messages).

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/167068983-c8bee24f-c66d-4341-8e06-01f496fa08c5.png)

added. ty

**Comment by chrisspiegl** [comment]
Looks good 👍.

**Comment by diegoveloper** [comment]
hey @steveseguin , first, thanks for creating this awesome tool for streamers! . I have one question, is there any way to automatic display a single message based on a donation/super chat?  I think this change only display the paid/donated messages in the full chat view, right?

**Comment by steveseguin** [comment]
**_&autoshowdonos_**
ie:
`https://socialstream.ninja/dock.html?session=XXXXXXXXXXXXX&autoshowdonos&autoshow`

![image](https://user-images.githubusercontent.com/2575698/181355877-c591a287-59c8-44eb-82c4-934299487557.png)

Please feel free to open a new issue if any arise.
