### ISSUE TITLE
in the last build 7TV emotes dont working on KICK

### ISSUE THREAD

**Issue by bloodsinc** [steveseguin/social_stream#154]
Like description said, in the last build 7TV emotes dont working on KICK, twitch and youtube is working

**Comment by steveseguin** [comment]
7TV seems to work for me with Social stream and Kick.  Please make sure 7TV has the appropriate permissions to access kick.com, as it wasn't enabled by default for me.

![image](https://github.com/steveseguin/social_stream/assets/2575698/e34540f9-456f-4089-a63c-cbd4ed1dd5a4)

![image](https://github.com/steveseguin/social_stream/assets/2575698/dc97320a-d769-4cbf-8d41-b43d5537b79a)

**Comment by bloodsinc** [comment]
yeah, have all permissions, but anyway dont working, will try to fix that
