### ISSUE TITLE
Vivaldi automatically disables Social Stream Ninja (FIXED)

### ISSUE THREAD

**Issue by Osaka78-on-GitHub** [steveseguin/social_stream#163]
SYSTEM
'Social Stream Ninja extension version 1.65.1' in 'Vivaldi 6.4.3160.47 (Stable channel) stable (64-bit)' on 'Ubuntu 22.04.3 LTS'

ISSUE
In Vivaldi address bar, Social Stream browser extension button automatically switched from green to red.

SYMPTOMS
Switch toggle from 'Extension Disabled' to 'Extension active'. A second or so later the extension button switches from green to red, menu still shows 'extension active' and green. OBS not receiving chat.

GUESS AT CAUSE
Vivaldi requires a Session Password when using a unique Session Channel ID

FIX
Go to vivaldi://extensions/ and 'Extension options' to enter unique 'Session Channel ID' as well as 'Session Password'. Give OBS the Session Password parameter. Password instructions here: https://docs.vdo.ninja/advanced-settings/setup-parameters/password

Deepest thanks to Steveseguin for all your brilliant workmanship. God bless you, Champion. 
Kind regards from Osaka78

**Comment by steveseguin** [comment]
This might be because you have the extension active somewhere else, with the same stream ID already. Setting a password will make your session unique.

**Comment by Osaka78-on-GitHub** [comment]
Yeah, thanks, Steve. You're right. We tested today and could reproduce the above behaviour by having two computers with identical session id and passwords. Good to know. Thanks again and kind regards
