### ISSUE TITLE
Enhance Fake Test Messages

### ISSUE THREAD

**Issue by diegoveloper** [steveseguin/social_stream#165]
Is there any way to do these things.

1- Generate a Fake Donation message? (I think right now is random between donation and no donation message).
2- Use a custom Fake message and custom Fake donation message (with custom username)?

Thanks for this great tool!

**Comment by steveseguin** [comment]
add &server to your dock.html link

then go here: https://socialstream.ninja/sampleapi.html?session=XXXXXXX

Create a fake meessage, then press one of the  "Server -> dock message" buttons

![image](https://github.com/steveseguin/social_stream/assets/2575698/1f38f5ae-b486-465b-987b-b188bcea568d)

If you want to add more fields, you can do so.

**Comment by diegoveloper** [comment]
Great! that worked!, one question, isn't there any direct link from the extension (UI) to the /sampleapi.html...? 
Thanks

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/5e29ede8-475a-4d6b-b1f3-831d7f7c4189)
There is

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/afa27779-1236-4d2f-8f33-46e8a1bc0911)

**Comment by diegoveloper** [comment]
Thank you!
