### ISSUE TITLE
Events not showing from tiktok chat

### ISSUE THREAD

**Issue by aarronlee** [steveseguin/social_stream#166]
TIKTOK events like "XXX has joined" are not showing on the chat but they did before...
Tried on standalone and also on chrome extension.

Events like "XXX has shared your stream" is showing correctly along with chat messages

**Comment by steveseguin** [comment]
Due to user feedback, you need to opt-in to that event for tiktok.  Ive included an image of the toggle

If its not working still, let me know

![image](https://github.com/steveseguin/social_stream/assets/2575698/f0a3f874-3f81-4434-9701-c8ca14fcbc36)

**Comment by aarronlee** [comment]
Hi,
Thanks for the quick reply..!


I have that option deactivated and it has never been activated… So with it deactivated it should work no?

like I said before, all other events show except for “XXXX joined the stream”

**Comment by steveseguin** [comment]
**Enable** the "Don't block "joined" stream events", along with the "Capture stream events and actions"

Most users did not want "joined events" showing up in their stream, so I've made it opt-in, rather than opt-out. This change would impact you if you recently updated.

**Comment by aarronlee** [comment]
Sorry for my ignorance but I have no idea on how to do that
