### ISSUE TITLE
TIKTOK CHAT BUG

### ISSUE THREAD

**Issue by WOLTPOA** [steveseguin/social_stream#17]
I can't capture tiktok live chat

**Comment by steveseguin** [comment]
It seems to be working for me at the moment.

- Can you ensure the extension is started (the menu for it should be green),
- Can you have the tiktok page open, so the URL matches **_tiktok.com/@YOURNAME/live_**
- Can you Reload the tiktok page, to ensure the code injected correctly?
- Can you check to make sure you are using the newest version of Socialstream: version 1.24.7

**If it doesn't work still,** 
- can you share the link that you are trying to capture with me?
- can you explain to me how  you're trying to use it?
- what language is your tiktok set to?

I'm on Discord at https://discord.vdo.ninja/  (channel #chat-overlay-support), if you prefer to talk there

![image](https://user-images.githubusercontent.com/2575698/168443576-11ee7246-b266-4cfd-848d-9b13562171e8.png)

**Comment by steveseguin** [comment]
Refreshing the page might be needed.  

I do see that the avatar images aren't working, so I'll try to fix both of those hiccups

**Comment by steveseguin** [comment]
I updated the extension; hopefully it works now without refreshing and the images work consistently.

You will need to re-download and reload it all to have it update tho

**Comment by WOLTPOA** [comment]
thx!
