### ISSUE TITLE
Bolt plus - Double message entry

### ISSUE THREAD

**Issue by techisgreat** [steveseguin/social_stream#172]
Hi , 
When some one is talking on chat i got triple and double of message all the time.
Is this possible to quick fix this ? 

![image](https://github.com/steveseguin/social_stream/assets/100486259/88eee215-3b38-4db6-b082-880a501c7b83)

**Comment by steveseguin** [comment]
what site is this?

Do you have multiple windows / tabs open of the site?

**Comment by steveseguin** [comment]
okay, I can replicate the issue with boltplus

**Comment by steveseguin** [comment]
I pushed a fix for boltplus. Update the extension or reload the source in the standalone app.

**Comment by techisgreat** [comment]
Omg you are so fast thansk !

**Comment by techisgreat** [comment]
Thanks for solving this very fast
