### ISSUE TITLE
3rd Party Twitch Emotes

### ISSUE THREAD

**Issue by testytrash** [steveseguin/social_stream#173]
Both BTTV and 7tv emotes don't seem to be working. I tried both the extension as well as the standalone app.
FrankerfaceZ is working well.

**Comment by steveseguin** [comment]
Which site? Twitch? youtube?

**Comment by steveseguin** [comment]
7TV / BTTV seem to be working with Twitch and SocialStream

![image](https://github.com/steveseguin/social_stream/assets/2575698/be072984-e86f-4342-9d13-977fb2547157)

![image](https://github.com/steveseguin/social_stream/assets/2575698/4e93c67a-73bf-4a24-866d-e6647ce9189f)

**Comment by testytrash** [comment]
![Untitled](https://github.com/steveseguin/social_stream/assets/58961849/429e4071-23e6-49da-89ae-d7a5dc281106)
Both twitch and youtube, and now I just noticed FFZ emote didnt load this time in the screenshot for me
Trying on this channel https://www.twitch.tv/popout/hachubby/chat?popout= and https://www.youtube.com/live_chat?is_popout=1&v=9N-UpaBBRUg

**Comment by testytrash** [comment]
Wait, I am so sorry. It was an issue with me not enabling the plugin.
