### ISSUE TITLE
sli.do - 

### ISSUE THREAD

**Issue by Ant-Productions** [steveseguin/social_stream#178]
Hey Guys,

Thanks so much for adding Slido!

We are having an issue for the below link.
This issue is that polls also get run from this page and the data stops

sli.do (https://app.sli.do/event/XXXXXXXXXXXXXX/live/questions)

can we use this view link (example below)and only grab the top msg as it comes in?
there will be a number that com in, the screen shot only shows 1 msg as an example
"https://wall.sli.do/event/rXuX1qTiQVRNrhDQJ8RdAA?section=557372e1-02ba-4098-9d49-dad83a41f4f4"
<img width="1385" alt="Screenshot 2024-02-06 at 12 49 25" src="https://github.com/steveseguin/social_stream/assets/110206599/bdfba872-8c63-47be-859f-1e33234f42f5">

Thanks heaps in advance!

**Comment by steveseguin** [comment]
Do you want these incoming streams marked as Questions?

**Comment by Ant-Productions** [comment]
we are pushing them to h2r graphics with Strip HTML on, so I'm not sure but think so

**Comment by steveseguin** [comment]
ah.  ty.

I'm trying to figure out how to set up that page in slido.  I don't have a paid account, so not entirely sure yet

**Comment by Ant-Productions** [comment]
we have just pushed 2 questions into the link above

**Comment by steveseguin** [comment]
Sorry, i didn't have the link open when you pushed, but also I'll need to refresh the page several times to properly add and test the integration.

**Comment by steveseguin** [comment]
nm. it worked after a few reloads

**Comment by Ant-Productions** [comment]
we can setup a slido event and add you as a admin if that would help?

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/7468ea91-0a85-40b2-b01f-5b6dce7684fe)

Done.  Let me know how it goes.

**Comment by Ant-Productions** [comment]
fantastic! thank you, guessing we need to download again what the current version?

**Comment by steveseguin** [comment]
If using the extension, you'll need to redownload.

If using the standalone app, you'll just need to reload

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/d0237a5b-c10b-42a7-877a-14e222e1c7bc)

**Comment by Ant-Productions** [comment]
Hey steveseguin

Thanks heaps for the work the other week,
it mostly worked, however as soon as our client pushes a poll at the end of a persons presentation
then goes back to the Q&A it no longer pushes the messages.

Slide also uses a feature where people can push up a question and it pops to the top,
is there any chance it could get sent again? we are using the “send to h2r server”

Here are some links to a test slido we’ve setup and you can approve questions and run test polls,
the video is an example of where we use it, we try and find the question they refer to...

Question display: https://wall.sli.do/event/2S1YK3JSXzCHAAfGvDjnoj?section=eabcbac3-932b-4bae-afa5-baa0e4b8b29b
 
Moderator Link: https://auth.slido.com/eu1/api/latest/the-auth/user/lifecycle-process/shareable-link/init?token=f17278bc7c93f4cb724e291c775d90d075fb8d215d5b1ce7ddf145d79ca640ba
 
Attendee Link: https://app.sli.do/event/2S1YK3JSXzCHAAfGvDjnoj
