### ISSUE TITLE
Chat stops scrolling if message is too long

### ISSUE THREAD

**Issue by ViolinGamer** [steveseguin/social_stream#179]
If someone posts a paragraph in Twitch/YouTube chat that is too long, the combined chat stops scrolling and I have to manually scroll to the bottom

**Comment by steveseguin** [comment]
Thank you for reporting the issue.  Until I get it fixed, you can try using &autoscroll 

If using any URL parameters like "&smooth" or anything else, it would help me to know them so I can include those options in my testing when trying to reproduce.  Are you using this as a dock in OBS?

**Comment by ViolinGamer** [comment]
Using &autoscroll fixed the issue, thanks!

Yes, I was indeed using this as a dock in OBS; my full parameter was "https://socialstream.ninja/dock.html?session=xxxxxxxxxx&color&compact&darkmode&fadein&hideshadow&noavatar&notime"

**Comment by steveseguin** [comment]
I pushed an update. Thank you for reporting the issue and providing details. If it still persists, let me know.

**Comment by ViolinGamer** [comment]
Awesome, thank you very much!
