### ISSUE TITLE
Unable to connect to Zoom meetings

### ISSUE THREAD

**Issue by ti-guru** [steveseguin/social_stream#180]
Steps to reproduce:
Add socialstream.ninja url to dock and browser element in OBS. Add Zoom meeting invite link in the "Other chat sites" panel in SocialStream app and press activate source. 

Expected behaviour:
Pop-up with meeting in browser window that the socialstream app can use to read zoom chat messages. 

What actually happens:
Meeting launches in native client and a pop-up displays with zoom page telling to either launch meeting or download client. Clicking the "Launch meeting" button another time gives an option of using the browser. Clicking this link connects to the meeting with Socialstreams browser window. However, dock in OBS does not pick up chat messages from other clients, but correctly displays fake messages generated from control panel in socialstream app. 

System:
Social stream client - Portable v0.1.13 
OS - Windows 11 Home 23H2 with Zoom client 5.17.7 from Windows store
OBS - OBS Studio 30.0.2 x64

**Comment by steveseguin** [comment]
I think I got it working.

zoom should I think work now in the ss app, without an update, however to prevent the desktop app version of zoom from trying to open also, I'll need to get a new standalone build out.  I've made the changes, but I will do a bit more testing and then build/release an updated version; probably within the next day or two? we'll see.

**Comment by ti-guru** [comment]
Closing this as latest build solves the problem. However, if choosing "end-to-end" encryption option for a meeting, there's no option to use the browser.
