### ISSUE TITLE
Twitch chat badges not displaying proper color

### ISSUE THREAD

**Issue by ViolinGamer** [steveseguin/social_stream#183]
Hey again! Thanks for your work on fixing the scrolling issue so quickly!

I've had this issue for a while, including on the newest update, where Twitch sub badges are not displaying the correct color. The Partner, VIP, Moderator, and Broadcaster badges are all appearing as white instead of their normal colors. I have a friend who also uses Social Stream and she was somehow able to get the colors to show up properly, but then we compared settings and had me use the exact same settings, which did not fix the issue for me. 

Here's the string I'm currently using: https://socialstream.ninja/dock.html?session=xxxxxxxxx&color&darkmode&alignbottom&notime&noavatar&compact&smooth

This happens in the OBS Browser Source, OBS Dock, and in the Google Chrome tab as well. My apologies if this is something that I can fix on my end.
![image](https://github.com/steveseguin/social_stream/assets/74080149/ae060a05-074f-4b6e-9f8a-6b5a53de30fa)

**Comment by steveseguin** [comment]
do you have any extensions installed? bttv, 7tv, or others?

**Comment by steveseguin** [comment]
i can replicate the issue using the FFZ extension, but not others, so I presume you are using that?

**Comment by ViolinGamer** [comment]
Ah, yes that was it. As soon as I uninstalled FFZ it fixed the issue.

**Comment by steveseguin** [comment]
I pushed an update to fix it. or I hope I did.  You'll need to update the extension though
