### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by Constantinowitsch** [steveseguin/social_stream#185]
Hi,

i have an issue with the standalone version. I was using 0.1.1 fine for quite a while. Then i updated to 0.1.5 and i keep getting this error with twitch:

Unhandled Promise Rejection
NonError: {
  name: 'TypeError',
  message: "Cannot set properties of null (setting 'href')",
  stack: "TypeError: Cannot set properties of null (setting 'href')/n" +
    '    at <anonymous>:181:44/n' +
    '    at new Promise (<anonymous>)/n' +
    '    at <anonymous>:9:10'
}
    at module.exports (C:/Users/Anwender/AppData/Local/Programs/SocialStream/resources/app.asar/node_modules/ensure-error/index.js:14:10)
    at handleError (C:/Users/Anwender/AppData/Local/Programs/SocialStream/resources/app.asar/node_modules/electron-unhandled/index.js:50:10)
    at process.<anonymous> (C:/Users/Anwender/AppData/Local/Programs/SocialStream/resources/app.asar/node_modules/electron-unhandled/index.js:130:4)
    at process.emit (node:events:517:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:294:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

I tired to go back to the old version, but the error is poping now up there too. Other chats are working fine tho.

I have no clue what to do.

Do you have any idea? Thank you ver much!

Kind regards
Constantin

**Comment by steveseguin** [comment]
Thank you for reporting. I'll fix and update if needed

**Comment by BlackKadabra** [comment]
Same here 0.1.15 ask to sign in on twitch then this message is displayed.

Had to uninstall and delete files in %appdata%, revert to 0.1.13 then readd twitch account.

**Comment by steveseguin** [comment]
I think if you delete the existing Twitch source in the app, and re-add it, it will be fixed now.

I've been working to add a websocket version of Twitch, and it seems to be breaking things, so I disabled it for now

**Comment by Constantinowitsch** [comment]
Thank you!
For now i use a workaround adding the chat with "Other chat sites" option. That works fine.

**Comment by steveseguin** [comment]
I'm not getting any errors myself at the moment, and unfortunately that error doesn't provide enough of a hint to know where it failed.

hrm..

Was this an error with the Twitch WSS option I just added, or the existing "activate source" source option?  Maybe delete what's existing there and re-add your username for Twitch. There might be a saved setting that is causing issues.

The new websocket option I hope reduces some CPU load, bloat, and allows me to do more things precisely.  It's going to take some time to get it up to parity with the existing option though, as I'm starting from scratch with it.

Thank you for reporting the issues and using the standalone version. I'll get it more stable as I flush out the core code.

**Comment by Constantinowitsch** [comment]
I just tired it again, so i can tell more about the error, but it disappeared and i can gladly not reproduce it.

Thank you ver much for your work and your replies! Your social stream is very helpful for my daily streams. 
Have a nice day :-)
