### ISSUE TITLE
Picarto support?

### ISSUE THREAD

**Issue by SixtyEmeralds** [steveseguin/social_stream#19]
Picarto.tv is a streaming platform I like to use when making Minecraft skins and hopefully when I start making music on tracker software.  I would love to have support for it on this plugin!  It would truly allow me to replace all my scenes with a singular chat window.

**Comment by 47ronin** [comment]
This may need adjustment. Initial usage requires right-clicking into chat popup and editing URL to allow for site login, then changing it back to the original current Picarto URL; otherwise default popout chat activates as signed out/read-only
