### ISSUE TITLE
Can't get facebook comments to show up

### ISSUE THREAD

**Issue by steven3363** [steveseguin/social_stream#2]
Hi Amazing tool. 

Hoping to feature it in a video. But I can't seem to get facebook comments to show.

I was testing it in 'Me Only' mode. 

Can you advise am I doing anything wrong

(Youtube is fine)

**Comment by steven3363** [comment]
I just saw in the instructions - set to viewer.

**Comment by steven3363** [comment]
Just checked, twitch-youtube-restream-chat-overlay works.
But this one does not. Even in viewmode.

**Comment by steveseguin** [comment]
Can you give it another go?

While it was working for me in my testing, I added in a few additional methods that might be more compatible. I also added support to the pop out chat window option.

You'll need to download and re-load the extension , then reload any open facebook page.

**Comment by steven3363** [comment]
Thanks! Works now. Haven't tried the pop-out for facebook if any issue ill advise.
An amazing solution, very elegant. Thanks!
