### ISSUE TITLE
Clear chat with a Stream Deck button

### ISSUE THREAD

**Issue by felippenardi** [steveseguin/social_stream#20]
Hello! I'm trying to figure how I can make a Stream Deck button that clears the current highlighted chat so I don't have to use the mouse (because often times I mistake and select another message instead)

Is there a http request I can make to clear the overlay of a chat given an ID?

**Comment by steveseguin** [comment]
https://github.com/steveseguin/social_stream#hotkey-midi--streamlabs-support

I've previously added support for StreamDecks via the use of the MIDI function.  

I haven't used it in a while, but I suppose it should still work and it has an option to do what you want.
