### ISSUE TITLE
Social Stream Ninja Opera and google chrome error help

### ISSUE THREAD

**Issue by Monketset** [steveseguin/social_stream#200]
This  error info Below Originally only appeared for me on opera browser. It now appears for google chrome and may appear for other browsers as well.

I followed the instructions to download and install the social ninja plugin it seamed to be working fine. 

However now I get the error  'content_security_policy': Ignored insecure CSP value "./thirdparty/tf.min.js" in directive 'script-src'.    

and the error   console.warn(sender);   simultaneously with Object Object Error.   

I'm not sure how to fix it or if social stream ninja even works on opera. 
 
Any help would be appreciated.

**Comment by steveseguin** [comment]
`the error console.warn(sender); simultaneously with Object Object Error.` was me forgetting to remove a debugging line. That error should be fixed now, however it wouldn't have caused the app to stop working.

The other errors can be ignored I think - -they are just warnings.

As per Opera,  I think it should work, however you may need to allow webrtc and/or disable your VPN if using one with it.  I mainly support Chrome, and other browsers often do things that interfere with Social stream.

If it is a webRTC issue, you can enable these toggles and it will bypass webrtc:
![image](https://github.com/steveseguin/social_stream/assets/2575698/a6b7e066-f670-48d3-9fca-078f860c96af)

**Comment by Monketset** [comment]
Thx for the help I'm a new social stream ninja user wasn't sure about those errors. I appreciate the Help.

**Comment by steveseguin** [comment]
Thank you for reporting the issue. I appreciate it.
