### ISSUE TITLE
Facebook Live Chat Not Working Since Update

### ISSUE THREAD

**Issue by MunayHealing** [steveseguin/social_stream#21]
When I saw there was a new update I downloaded it and added it to my Chrome extensions and am getting the attached errors. When loading the Dockable Stream Chat Link in my browser, it doesn't pull any any comments from my Facebook Live and the Message Overlay Window is just white. Is there a fix for this? It was working beautifully 3 days ago pulling in all of my comments. The only thing it wouldn't pull in was profile pictures/avatars on Facebook. Which was perfectly ok because it was still showing the User Name and Comments. Now nothing is loading. I uninstalled and re-installed the actual zip file numerous times (ensuring to delete previous versions and clearing my browsers cache) and followed the video to no avail. It's also showing an error in the Extensions window. If I turn on any of the features such as 'Show Channel Icon' or try to change the back ground color of the chat, and chat color, the Dockable Stream Chat browser is totally blank not even showing the Clear Overlay, Pause, Auto etc.. icons at all. It's just a plain black screen. This was the ONLY program I could find that worked with OBS to pull in single user comments and not sure what to do to make it work again. Any help is GREATLY appreciated! 
![Errors with Extension](https://user-images.githubusercontent.com/108105030/175755298-4900cc70-aa78-41cd-8a57-57f789ebab82.jpg)
![Errors with Extension2](https://user-images.githubusercontent.com/108105030/175755297-c77d8f64-c3e0-49a5-a1c2-853df011b893.jpg)
![Errors with Extension3](https://user-images.githubusercontent.com/108105030/175755299-75bb16c3-f829-44e6-93d9-4769b7892377.jpg)

**Comment by steveseguin** [comment]
You can ignore those warnings; they will persist until I upgrade from the v2 to v3 browser extension api. 

I pushed a new update for Facebook just now; reduced some CPU load and got avatars working again, but I'm not entirely sure there were other problems.

It seems to be working for me at the moment, so let me know if the issue continues.

**Comment by MunayHealing** [comment]
Thank you so much for the prompt response and for making this tool! It was the one thing that I just couldn't find anything that would work for Facebook in particular. This is really going to help with interacting with my audience, especially as a coach. You made that possible and I'm so grateful for your help! Long time future customer here and will be recommending this to all my fellow friends who use Facebook Live & OBS! I will give it a go and let you know :)

**Comment by steveseguin** [comment]
Looking forward to hearing if it works or not. If not, we can dive in with some added debugging together.

Thank you kindly

**Comment by Arenthous1** [comment]
Ok so I did this and everything else seems to be working except being able to see the comments on the screen. The overlay is still blank.

**Comment by steveseguin** [comment]
> Ok so I did this and everything else seems to be working except being able to see the comments on the screen. The overlay is still blank.

Sorry, I'm not sure I understand you're problem.  This Github issue was about someone else having Facebook suddenly not work after an update.

What issue are you having? Please open a new Github issue and describe what you've tried if unrelated.  I don't know if just the overlay is blank, or whether its just facebook you're having issues with, etc.

You can also join the Discord, at discord.vdo.ninja and message me in #chat.overlay-support

**Comment by steveseguin** [comment]
It appears to be working for me at the moment.  If still having problems, join the discord and we can debug the issue

![image](https://user-images.githubusercontent.com/2575698/180659208-369fcb92-afb9-48da-a577-920b7d99933a.png)
