### ISSUE TITLE
Whatsapp emojis not working properly in Socialstream

### ISSUE THREAD

**Issue by markusnygard** [steveseguin/social_stream#211]
Emojis are not showing in Whatsapp-message in Socialstream if there also is text in the message.
So text - emoji -text shows text -"empty" - text
emoji - text shows "empty" - text
neither animated gif nor stickers shows
if the message is just 1 or 2 emojis then it shows OK
if the message is 3 emojis then just 2 emojis shows (Opera GX) in Chrome 3 shows OK
if the message is more than 3 emojis then message shows up empty
Tested on both using extension in Opera GX-browser LVL5 (core: 107.0.5045.89) & Chrome Version 124.0.6367.61 (Official Build) (64-bit)

**Comment by steveseguin** [comment]
I pushed an update.  
![image](https://github.com/steveseguin/social_stream/assets/2575698/b5ff0424-48f9-4cf9-841f-a6a6569d85f6)

I think it's working now, however, it may not work with every emote. it worked with the ones I tested however

changes:
https://github.com/steveseguin/social_stream/commit/039a0040658304c3c5b0686c832ce34ba26aec25

**Comment by markusnygard** [comment]
Just tested with Opera GX and can comfirm it seams to work properly. 
Thank you
Markus
