### ISSUE TITLE
block  words

### ISSUE THREAD

**Issue by seminareenvivo** [steveseguin/social_stream#213]
Hello, it would be very helpful if you could block specific words.

**Comment by steveseguin** [comment]
At the moment, to do this with the extension, rename the file "badwords_sample.txt" to "badwords.txt" in the social stream folder; where ever you extracted it to I guess.

Update the file with the words you want to filter.

Reload the extension or restart the browser.  Then enable block bad words option in the menu.

I'm open to considering other ways of doing this.

**Comment by seminareenvivo** [comment]
How do I enable the option to block bad words in the menu?

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/b61ac4a9-470f-4ddc-a310-d254b65329fc)

In the general -> visibility section

By default there is already a long list of common bad words, but you can add your own with badwords.txt

**Comment by seminareenvivo** [comment]
Excellent, it worked well for me! Thank you very much, but is there any possibility that the asterisks DO NOT appear? Since when I use text to speech I don't want it to be heard

**Comment by steveseguin** [comment]
I can skip messages that have profanity in the TTS

Or I can add an option to do remove the word and not put an asterisks 

or I can have the TTS ignore asterisks or I can have the TTS say "Bleep" when it sees a ***

**Comment by seminareenvivo** [comment]
It would be great for me if the TTS ignored the asterisks.
I use your extension 4 hours every day and it is the only thing missing to make it perfect. You are the best!

**Comment by steveseguin** [comment]
updated
