### ISSUE TITLE
PeerTube LiveChat version 9.0 changed URL scheme. Need to update which URL triggers PeerTube LiveChat capture

### ISSUE THREAD

**Issue by dannekrose** [steveseguin/social_stream#218]
Starting in PeerTube LiveChat plugin version 9.0, the url scheme has changed.

Old scheme: https://*/plugins/livechat/router/webchat/room/
New scheme: https://(domain)/p/livechat/room?room=(roomID)

This is a request to allow PeerTube Livechat plugin version 9.0 and newer to also be captured/triggered for Social_stream use.

Thank you.

**Comment by steveseguin** [comment]
https://github.com/steveseguin/social_stream/commit/8f2dd666d82f1bb69ee3c785dad7dcbd483dad7d

I made the changes, but did not test.  If you can provide a site with the 9.0 running on it , with a chat available to test in, I can do so if there is more work needed

Thank you for providing the details.

**Comment by dannekrose** [comment]
I just testing with the new changes and the PeerTube LiveChat is being captured correctly now with the latest PeerTube Livechat 9.0.x plugin.  Thank you!!
