### ISSUE TITLE
Override avatar if `avatarfake` has an image URL on message view

### ISSUE THREAD

**Issue by diegoveloper** [steveseguin/social_stream#224]
When `avatarfake` is set it works fine in the dock, but when the message is displayed it still uses the twitch avatar if it exists.

https://github.com/steveseguin/social_stream/assets/4898256/ebb0d65a-7515-4f83-96dd-14fb70c10d36

**Comment by steveseguin** [comment]
Are you using index.html or featured.html ?

I've been re-organizing the structure of the files and index.html has been replaced by featured.html, and so index.html won't be getting updates anymore.  I will forward users from index to featured automatically in a few months from now.

If it doesn't work with featured.html though, let me know and I'll do more testing

**Comment by diegoveloper** [comment]
my bad, I was using index, it works perfectly with featured.html! thank u

**Comment by diegoveloper** [comment]
I think one of the latest updates broke this change :/, I'm using featured.html but now I can't get the custom avatar.



Uploading Screen Recording 2024-06-16 at 11.10.52 PM.mov…

**Comment by steveseguin** [comment]
https://github.com/steveseguin/social_stream/commit/0a63f4b520da51587bc5fce59b7f9c9c6f25d7de

Thank you.

I pushed an update, as shown above. It should go live in a minute.  

I dont think anything broke, but it looks like I only added the fake avatar to one of the API example buttons; not all of them. I corrected that.

**Comment by diegoveloper** [comment]
I tested the latest code and the dock shows the right avatar but the featured message uses twitch avatar.

![Screenshot 2024-06-16 at 11 34 53 PM](https://github.com/steveseguin/social_stream/assets/4898256/edfd4baa-34ec-4fb3-a0e8-5aca2226ca5e)

**Comment by steveseguin** [comment]
ah, okay. So two issues

I pushed a fix.  There was a bit of a conflict between the needs of different users, but I think I have the logic sorted out now to handle both use cases.

**Comment by diegoveloper** [comment]
thank you 🙏
