### ISSUE TITLE
Unhandled Promise Rejection on Pilled, Rumble, Odysee Popouts

### ISSUE THREAD

**Issue by jaseRival** [steveseguin/social_stream#225]
I keep getting this message when trying to add those three platforms:

Unhandled Promise Rejection
Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at node:electron/js2c/sandbox_bundle:2:58441
    at IpcRendererInternal.<anonymous> (node:electron/js2c/sandbox_bundle:2:52634)
    at IpcRendererInternal.emit (node:electron/js2c/sandbox_bundle:2:34768)
    at Object.onMessage (node:electron/js2c/sandbox_bundle:2:50712)

**Comment by steveseguin** [comment]
Thank you for reporting the issue.

You can probably go back a version until I fix it.

**Comment by steveseguin** [comment]
I found the problem. I'll have an update out soon

**Comment by steveseguin** [comment]
https://github.com/steveseguin/social_stream/releases/tag/0.1.27

**Comment by jaseRival** [comment]
Thank you!
