### ISSUE TITLE
Twitch Chat not working, Youtube works fine.

### ISSUE THREAD

**Issue by Neipas09** [steveseguin/social_stream#23]
Twitch chat messages won't load in Dockable streaming chat link.
If I try it with Youtube, the messages load with no issues.

I've even tried popping out Twitch chat AFTER loading Youtube chat messages and verifying they are working.

![image](https://user-images.githubusercontent.com/58871039/180580420-9923814d-a918-41b8-ae41-68a77a7b40e3.png)
****

**Comment by steveseguin** [comment]
It appears to be working for me.

Do you have other browser extensions installed? Sometimes other extensions designed for Twitch chat can cause conflicts.

**Comment by Neipas09** [comment]
No, the only other extensions I had installed were BetterTTV and FrankerFaceZ

**Comment by steveseguin** [comment]
I installed FrankerFaceZ and it broke things for me.  I'll need to add support for it, as it breaks the twitch chat, changing it so I can't recognize it anymore.

**Comment by Neipas09** [comment]
> I installed FrankerFaceZ and it broke things for me. I'll need to add support for it, as it breaks the twitch chat, changing it so I can't recognize it anymore.

That was it. I turned off FFZ and it's working now.
Thanks for the help!

**Comment by steveseguin** [comment]
I pushed an update; will require re-installing the extension, but it might now work with FFZ?  Hit me up if not or if I broke anything.
