### ISSUE TITLE
Filter Emotes / Whitelist Emotes

### ISSUE THREAD

**Issue by chrisspiegl** [steveseguin/social_stream#245]
An addition could be to be able to filter the emotes wall so that either certain emoji will not be shown on the emotes wall  or only a select view emotes are allowed to be shown on the emotes wall.

I can see both being useful but pretty much to the same effect — especially if you want to not get any 💩 or 🍆 flying around.

**Comment by steveseguin** [comment]
`&bademotes=🍆💩`

Added this as an option to the emotes.html page

**Comment by chrisspiegl** [comment]
Nice, that was quick 👍.

**Comment by chrisspiegl** [comment]
I confirmed it to be working 👍.

Is this also a text field in the extension/application for people to easily discover?

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/1f999ba6-9efa-4489-bd50-7656e16f7414)

There is an emotes-wall specific option. you'll need to update to see it if you haven't already

**Comment by chrisspiegl** [comment]
Perfect. Then this is implemented and done. Gracias.
