### ISSUE TITLE
Idea: Amazon Practice Chat Overlay

### ISSUE THREAD

**Issue by chrisspiegl** [steveseguin/social_stream#246]
I just tested the Amazon chat integration, and it's working on public live streams.

However, Amazon also offers a Practice Chat for people who want to test their live stream. Maybe this URL could also be added to import the chats? The chat page I think works the same way as the regular Amazon live, just in private.

The URL for practice live streams looks like this:

`https://www.amazon.com/b/?node=INTEGERNUMBER&broadcast=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/2c5c5a93-f7d1-4891-ae2f-49ebc9fe5d7b)


Added it, but haven't tested it

**Comment by chrisspiegl** [comment]
I'll test it in the coming days and let you know if it works.

**Comment by chrisspiegl** [comment]
Tested with practice mode and can confirm it's working.
