### ISSUE TITLE
Suggestion: Mosaic/Blur for other platforms.

### ISSUE THREAD

**Issue by bensam123** [steveseguin/social_stream#249]
Hello, really enjoying the plugin and I feel as though social interaction between platforms is incredibly important. Obviously showing other platforms chats on twitch is against the ToS, but as an idea that I think gets around it, can we get a mosaic/blur option for chats not Twitch?

This allows us to show that we're interacting with other platforms to Twitch without showing the platform or the chat, while showing how active those platforms are. I know there is an option to remove the other platforms chats, but for those of us that want something a bit more spicy I think this fits the bill.

**Comment by steveseguin** [comment]
It's a fun idea. Thank you

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/bd510366-426e-498f-8645-833fc3431fee)
![image](https://github.com/steveseguin/social_stream/assets/2575698/55eb397e-fe33-45f0-82d6-849603ee7186)

or `&blur=5`

**Comment by bensam123** [comment]
Looks great.

**Comment by bensam123** [comment]
We going to see this pushed live soon? Would love to try this out.

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/b0ef2569-790f-4422-b887-65f406a6dde1)


I believe it was already live when I mentioned it the other day. If using the extension, update.

**Comment by bensam123** [comment]
Got it, was on a old version, thanks.
