### ISSUE TITLE
Suggestion + Remove : Verticalpixelzone.com

### ISSUE THREAD

**Issue by verticalhost** [steveseguin/social_stream#250]
We propose adding Verticalpixelzone to the list of supported platforms for Social_stream. Verticalpixelzone is a comprehensive Twitch-like streaming platform built using advanced technologies like Next.js, React and livekit.

[VerticalPixelZone](https://verticalpixelzone.com)

We also want to tell you VIMM.TV is close recently so it's no more.

If you want to inspect how chat are working you have to start stream to start chat aswell be cause of livekit. 
https://docs.livekit.io/home/

VPZ dont have any of API for chat yet but on future.

**Comment by steveseguin** [comment]
Vimm.tv closed? oh, thank you for letting me know.  That community was using Social stream quite a bit; sad times.

I should be able to add support.  If you update the chat in the future, just let me know so I can update my support as well.

**Comment by verticalhost** [comment]
The website is now open. 
We have re-built website from scratch and now it's pre-alpha launch. 
We use pop-up chat like this : https://chatouille.verticalpixelzone.com/?room=gaminghype6052&username=Anonymous 
Using Socket.IO technologies so you can use inspection tools to grab information.
