### ISSUE TITLE
Channel points

### ISSUE THREAD

**Issue by KibaTheBarbarian** [steveseguin/social_stream#258]
Be able to see Channel points redemption from TTV

**Comment by steveseguin** [comment]
![image](https://github.com/steveseguin/social_stream/assets/2575698/f0f32c1b-3264-4b93-9494-44956a32e478)

I thought I had channel point redemptions for twitch. You may need to enable stream events to show them.

I do have more work to do on polishing how they look however

If its still not working, I will spend more time on it

**Comment by KibaTheBarbarian** [comment]
ok it works other note I discovered does the application support Twitter pop out chat

**Comment by steveseguin** [comment]
It should support x.com, or did as of last week or so.  I dont recall x.com having a pop out chat, but if it does now, then I'm not sure if I support it yet.

I can look into supporting it, but is this a producer-side chat? a viewer-side chat?  Any details  you can provide would help

**Comment by KibaTheBarbarian** [comment]
![Capturex](https://github.com/steveseguin/social_stream/assets/20373705/7fb8cff9-072d-4b75-8ee7-58743318620b) I do live stream on Twitter when I go live keep an eye out and you can test it but you can only interact with the chat when the live stream is going since I livestream on Twitch I have it only I can see. it going live soon

**Comment by steveseguin** [comment]
When you go live I can test.

**Comment by KibaTheBarbarian** [comment]
i am live

**Comment by steveseguin** [comment]
I pushed an update.  Once you update and reload, it should work with the pop out chat

**Comment by KibaTheBarbarian** [comment]
ty so much i hope i help you out
