### ISSUE TITLE
The first Twitch emote is always moved to the end of a message

### ISSUE THREAD

**Issue by blazex224** [steveseguin/social_stream#263]
I cannot find a setting for this. Is this a bug?

First image is what was actually sent through Twitch, second image is the extension

![image](https://github.com/user-attachments/assets/4c237e8b-93a5-4b79-960b-799a7df02117)

![image](https://github.com/user-attachments/assets/800d1fec-789a-4a95-9195-dd08a9303284)

The following image shows how it is only the first emote that is moved to the end of a message

![image](https://github.com/user-attachments/assets/18f0c540-7e94-4869-86a7-f003f34f58d5)

Using the latest version

Thanks for any help with this

**Comment by steveseguin** [comment]
It's a bug. Are you using BTTV/7TV by chance?  It was probably introduced by the recent 7TV/BTTV changes I made. 

Thank you for reporting the isuse.

**Comment by blazex224** [comment]
Hi, yep! I am using 7tv (and BTTV which is included in the 7tv extension of course). Tested using normal emotes, but it makes sense that this could be from 7tv

**Comment by steveseguin** [comment]
I pushed an update. If problems persist, please be sure to let me know.  Thank  you kindly
