### ISSUE TITLE
Delay showing messages, allow manually deleting before showing

### ISSUE THREAD

**Issue by SpriteOvO** [steveseguin/social_stream#264]
Hi, recently I'm trying to stream on both bilibili and YouTube at the same time and integrate both chats into OBS. I found this project and it might be a good match for my case, thank you for your work!

There's just one issue, and I'm not sure if there's a solution for this. As we all know, bilibili is a platform operating in China and it has a strict censorship system. Some of the messages on YouTube chat are not suitable to be displayed on bilibili (otherwise the streamer or room will be banned). Word blacklists can't completely stop these kinds of messages because there are always ways to get around the filters.

I was wondering if there was a feature / API that would allow a 15 second delay for new messages to show up in OBS, which would end up not appearing in OBS if the message is deleted via the dashboard during this time.

Or is there an alternative solution to this X problem? Any guide would be much appreciated.

**Comment by steveseguin** [comment]
![image](https://github.com/user-attachments/assets/38e4983c-6114-423a-8b2e-228ed4a3de92)

I added &delaytime=10000 as an option just now for you.  If you have this added to your on-air dock.html page, you can have moderators who use a dock without the delay option to delete messages before the reveal.

It needs testing, and it's not 100% perfect, but I hope it is a start

Another option is to have "pinned" messages appear only on stream, and just manually pin the messages you want to appear.

**Comment by SpriteOvO** [comment]
Wow! Amazingly fast implementation! Thanks, I'll test if it works ASAP..

**Comment by SpriteOvO** [comment]
That's really cool! I tested it and it works perfectly at least for my current use case. Thank you again!
