### ISSUE TITLE
Multichat relay communication

### ISSUE THREAD

**Issue by a15mni** [steveseguin/social_stream#265]
I've been using this for years and its been great combining the chats but is there a way for them to communicate with each other? for example twitch chats being sent by maybe a bot to youtube chat and vice versa so that the communities wont be divided when im streaming.

**Comment by steveseguin** [comment]
![image](https://github.com/user-attachments/assets/4f1f29b3-a9c8-4a9b-b391-6d846bbc1608)

I dont recommend using it, but there is an option.

**Comment by a15mni** [comment]
Nice! thank you!
