### ISSUE TITLE
Any chance of a Linux version of the app?

### ISSUE THREAD

**Issue by MichaelGame-Dev** [steveseguin/social_stream#266]
Just curious if there was an opportunity to have a Linux app as well. I generally use firefox so will have to set this up in something like Brave to make this work currently. Would personally much prefer a standalone app so I don't need yet another browser tab/window open.

Edit: I guess you can close this. I see there's an app image. I have it installed, it's running. I do have to actually try to figure out how I go about adding chats to it. Do I need to pop out chats like the browser extension?

Edit 2: Twitch at least works from a brief test! App image or flatpak is a great choice on Linux for this. Thanks so much!

**Comment by steveseguin** [comment]
I have an updated version of it out now.

I haven't tested on LInux, but I have on mac/pc.  Some sites require it to be popped out, even though you can then "hide" it without issue.  Others, like Tiktok, have a websockets option, which doesn't require a pop out as its not scraping.

https://github.com/steveseguin/social_stream/releases
