### ISSUE TITLE
[Bug] Chat Names Randomly Show Up Small

### ISSUE THREAD

**Issue by TheRenegadist** [steveseguin/social_stream#267]
So I tried your standalone chat software for the first time today and I gotta say, it's a real game changer. I did run into a couple issues, one of which being that for whatever reason people's names in the chat turn up smaller sometimes and I haven't been able to figure out why.

![image](https://github.com/user-attachments/assets/dd0b14d7-120a-4655-86dc-be84b306793a)

You can see here it happens seemingly at random even when it's the same person typing, I stream to both Odysee and Twitch and it seems to happen for both at random. Is this a bug or something I accidentally enabled? If there's any other info you need I'd be happy to send it over.

Here's my settings:

![image](https://github.com/user-attachments/assets/88c973be-e727-4b5f-917f-fe5d64ed32ce)
![image](https://github.com/user-attachments/assets/093e5bd6-2528-43ff-abeb-302dd0f62244)

**Comment by TheRenegadist** [comment]
Update: It seems to only do this when the person sends a small message, if they send a larger message it shows normally. Unless this is a setting I have ticked, this seems like a bug not to mention the avatar display is also off center.

![image](https://github.com/user-attachments/assets/eb310a58-18f1-4907-b745-0edcc18c975b)

**Comment by steveseguin** [comment]
Thank you.  I'll look more into this.  Names normally are made small if they don't fit, but something is definitely broken here.  I'll spend a bit of time on it now

**Comment by steveseguin** [comment]
I think &split and &compact, when used together, are causing it.  I'll try to fix it

**Comment by TheRenegadist** [comment]
Thanks steve, hope the other two issues I made can be addressed as well because I really love this software.

**Comment by steveseguin** [comment]
![image](https://github.com/user-attachments/assets/da89f751-d644-4244-9c18-8cbdcfe96e0d)

Some of these issues are fixed, I hope.  More testing is needed, as there are a lot of styles/features/functions that may conflict.  If you find more, please let meknow

**Comment by TheRenegadist** [comment]
Will do, once the update comes out I plan to do a lot of testing.

**Comment by steveseguin** [comment]
> Will do, once the update comes out I plan to do a lot of testing.

The update for the above changes was automatic; the dock.html page is hosted, so the changes are applied already online.

The other feature requests, such as outlining of avatars based on source location, will probably not be completed all that soon tho; so many things to do

**Comment by TheRenegadist** [comment]
Oh that's really cool, it's no wonder by the end of my stream everything looked like it was working as it should lol.

Is it possible to also get the avatar sides switched and the elements centered or have the option to do so mentioned in https://github.com/steveseguin/social_stream/issues/270

**Comment by TheRenegadist** [comment]
After several streams this issue is 100% fixed.
