### ISSUE TITLE
Create a CHANGELOG file to see what's new on the newer versions

### ISSUE THREAD

**Issue by diegoveloper** [steveseguin/social_stream#27]
Hi, I usually see that there is a new version when I click on the Social Stream Ninja button on chrome, and it says "There's a new version available (new vs old)", but I'm not sure what are the changes until I check all the commits.

It would be easier to track the changes using a `CHANGELOG` file.

**Comment by steveseguin** [comment]
Thank you for the suggestion.  It's definitely something I'll be keen on adding.  A change-log specific for socialstream that's linked into the app would be valuable.

Commits are one place to see the updates.

I also have updates for vdo.ninja + socialstream here: https://updates.vdo.ninja/  I might be able to split the updates up, but they are currently combined.

Long term I'll try to have things auto-update perhaps; haven't decided that yet tho.
