### ISSUE TITLE
[Feature Request] Have option for avatars to appear on the left of the username without the "big" option selected

### ISSUE THREAD

**Issue by TheRenegadist** [steveseguin/social_stream#270]
Referencing the screenshot from my other issue, I don't think it makes sense to have the "Username:" and then follow that up with the avatar rather than the text itself, can an option be added to include the avatar on the left of the username rather than the right without selecting the option that makes the avatar big?

The avatar positioning themselves also needs adjusting as it seems they show up lower than the name itself rather than centered with it. Looks like the badges also aren't centered either.

![image](https://github.com/user-attachments/assets/eb310a58-18f1-4907-b745-0edcc18c975b)

With some crude Photoshop work I imagine it would end up looking something similar to this:
![image](https://github.com/user-attachments/assets/49617e7b-c194-421a-9da9-a43946cdcf8b)

Maybe there could be a little more space between the website badges and the avatar so it's not so close together.

**Comment by steveseguin** [comment]
![image](https://github.com/user-attachments/assets/c716dfd9-9b13-4034-ba38-e8a7af4757ee)

It's still a work in progress, but the badges/source are on the left side of the name now, by default, when using the &split option

**Comment by steveseguin** [comment]
you want the avatar on the left hand side too? okay.

**Comment by TheRenegadist** [comment]
I figured that make sense, default chats for most websites go by avatar, username, and then the message.

**Comment by steveseguin** [comment]
![image](https://github.com/user-attachments/assets/b0afbe5f-37bc-43c3-852e-6a7846bad4dd)

**Comment by TheRenegadist** [comment]
Been doing some testing, so far so good. I'll go ahead and close the issue because the avatars are in-fact, on the left side of the name and it seems things are centered.
