### ISSUE TITLE
Issue - Social Stream Overlay

### ISSUE THREAD

**Issue by SCU-Leinad** [steveseguin/social_stream#31]
The Social Stream Dashboard is working as expected.  But when I tried using the Social Stream Overlay on OBS, the messages are NOT showing up on the Browser source.

**Comment by steveseguin** [comment]
Hey @SCU-Leinad 

There's a few reasons I can think of this happening:

1. If you're using a Mac, and you are loading the dashboard as a locally hosted file into OBS, OBS for Mac will fail.  Works fine on PC, and should work fine if hosted via socialstream.ninja though.

2. OBS's browser source has crashed.  Restart OBS completely and trying again may work

3. The session ID is incorrect; this might happen if re-installing the socialstream extension, as the session ID is reset then.

If none of those are the cause, we can dig more into this. I just tested it now and it does seem to be working.

![image](https://user-images.githubusercontent.com/2575698/188292299-37039453-32ea-4f04-b52c-c327eb68508e.png)

**Comment by SCU-Leinad** [comment]
Thank you so much for the feedback.  I am using PC and have no problems with the chatbox.  The issue I am reporting is regarding the single message Overlay.

![image](https://user-images.githubusercontent.com/112785825/188293612-c52e919d-144f-49e2-a5ea-95384530f64d.png)
Dashboard is working.


![image](https://user-images.githubusercontent.com/112785825/188293654-62b14e9a-aeb6-42fd-8279-e8bb2bf84ced.png)
Overlay is not working

![image](https://user-images.githubusercontent.com/112785825/188293711-0001dcc7-714b-4a1d-8f4a-2283d7d0e213.png)
This is the message overlay I am pertaining to and it works before the update

**Comment by steveseguin** [comment]
It still seems to be working for me.  I just tried the single message overlay and it's working with my OBS.

https://socialstream.ninja/index.html?session=F9SQm9E7Rj&showtime=20000&fade&center&showsource&aligntop
![image](https://user-images.githubusercontent.com/2575698/188298787-7406205f-ad78-42a5-b3c9-b6d850c62184.png)

![image](https://user-images.githubusercontent.com/2575698/188298854-f97a82dc-c3f0-42c8-af44-dba69e9f32bb.png)

Do you see any errors in the index.html page if you inspect it?

**Comment by SCU-Leinad** [comment]
Thank you so much again for the feedback.  I think I know now what I am missing.  I think I got used to the "AUTO" post from the old one.  That is why I was waiting for the message to appear.  I need to click the message in order for the single message to appear.  

Feedback: Can you have the "AUTO" feature back or have the message automatically posted?  I mean it's hard to click the message while I am playing a video games so that the viewers can see the message especially when I am interacting with them.  They sometimes ask question and I response back by saying it on live stream while playing.  I am NOT sure why we need to click a message in order to appear in the OBS.  Again thank you so much for the feedback.

**Comment by steveseguin** [comment]
I think auto-show is already available via &autoshow
![image](https://user-images.githubusercontent.com/2575698/193446495-7b4c3ae6-a2f8-471f-8c2e-19b41296fe2d.png)

Let me know if not.
