### ISSUE TITLE
ChatGPT and Google Gemini support

### ISSUE THREAD

**Issue by MStankiewiczOfficial** [steveseguin/social_stream#311]
Since the app supports Ollama, it would be good if it also supports ChatGPT and Google Gemini via API.

**Comment by steveseguin** [comment]
I have both of those working internally with it, and the intent is to allow users to use Gemini/GPT, yeah. You're the first to ask for it, so I'll publish that code after I clean it up a bit.

Thank you

**Comment by steveseguin** [comment]
added ChatGPT + Gemini support to the LLM options to SSN, so if you can't handle Ollama locally, you can now get pay to have those services to the lifting for you.

- streaming responses work, when using the chatbot mode at least. No point in streaming with normal chat responses
- I've been playing around with image recognition support, but I haven't really figured out a good use case there yet. If you have a use for it though, or other llm features, let me know

![image](https://github.com/user-attachments/assets/1e5cf52d-5bbf-4edb-91b9-5efb98626f60)
