### ISSUE TITLE
Small dock view (HTML)

### ISSUE THREAD

**Issue by ProtocolLive** [steveseguin/social_stream#315]
First column its too big
![image](https://github.com/user-attachments/assets/dcb7b1eb-f295-435a-8f8c-0a48ee359f7b)

**Comment by steveseguin** [comment]
Add &compact to the URL or use CSS to make the space smaller.  

![image](https://github.com/user-attachments/assets/cd65b0d1-ff79-45b4-8653-8037db94a0b9)

It normally auto-adds compact if the window width is narrow, so its normally not needed to add &compact.   Maybe I can adjust things a bit there to fix it.

If &compact isn't what you want, let me know and I can try to support it

**Comment by ProtocolLive** [comment]
The &compact solved here. Thanks
