### ISSUE TITLE
Rutube Chat not works anymore

### ISSUE THREAD

**Issue by eyeofal** [steveseguin/social_stream#316]
Used version 1.80.18 and it's works fine, but now not works. I tried latest version today - 3.4.3 , and it's still not works (

**Comment by steveseguin** [comment]
![image](https://github.com/user-attachments/assets/a9d1c41c-db9f-48c0-9611-f6ed411a1b38)
let me know if it still doesn't work after updated

**Comment by eyeofal** [comment]
Not work again

**Comment by steveseguin** [comment]
pushed a fix. i think.
