### ISSUE TITLE
Tiktok popup needs to be on foreground to update chat

### ISSUE THREAD

**Issue by a15mni** [steveseguin/social_stream#319]
Hello! 

I've been experiencing this for a few days now and as the titles says the pop up needs to be on foreground for it to update like normal(realtime). If its at background as usual (not minimize ofc) it takes a few minutes to update the chat. Sometime it hangs Google Chrome if the chat is too fast. ive tested with fast volume twitch chat and the problem doesn't occur.

Thanks in Advanced.

**Comment by steveseguin** [comment]
The standalone app solves this issue with Tiktok, and also includes a "websocket" alternative way to capture the chat that uses less resources.

In the browser normally, I'm not sure yet if I can fix this issue.
