### ISSUE TITLE
VK Play Live made rebranding today and now chat is not working

### ISSUE THREAD

**Issue by eyeofal** [steveseguin/social_stream#321]
Hello. Originally it was vkplay.live now it's live.vkvideo.ru and now chat not working (

**Comment by steveseguin** [comment]
update and try again

**Comment by eyeofal** [comment]
Thanks, works. 
But there double colon after nickname. And logo of VK , not VK Video Live

VK Video Live logo https://static.live.vkvideo.ru/static/favicon.png

**Comment by steveseguin** [comment]
![image](https://github.com/user-attachments/assets/c2f8d3d8-5584-401d-8245-9d65fb7821b4)
