### ISSUE TITLE
Private self-hosting for social_stream

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [steveseguin/social_stream#33]
Hello, interesting project!
As far as I understand the backend is not opensource?
Do you plan to opensource? 
If suddenly something happens to the domain and the hosting is not renewed, this service will stop working. Just insurance against bus factor.

**Comment by steveseguin** [comment]
The backend is based on VDO.Ninja, which is open-source and something you can fully self-host.

https://github.com/steveseguin/vdo.ninja/blob/develop/install.md

I'd recommend deploying vdo.ninja to https://vdo.yourdomain.com, as this keeps issues with cross origin at bay; at least that's what I'm doing with socialstream.

**Comment by 0x4E69676874466F78** [comment]
@steveseguin Thank you very much for your fast reply and have a great day!
