### ISSUE TITLE
Random Icon

### ISSUE THREAD

**Issue by BRN2018** [steveseguin/social_stream#34]
When using Social Stream dock, after showing a chat then pressing "Clear current overlay" the chat goes away as it should, but then is replaced by a strange random icon. I just installed the latest version. Any thoughts?![image](https://user-images.githubusercontent.com/89499600/196523196-2092349a-afae-451f-8a69-69cc3e9a4bcd.jpeg)

**Comment by steveseguin** [comment]
apologies. Can you try again?

**Comment by BRN2018** [comment]
That did it!! Boom. You are amazing, by the way. The work you do is simply incredible. Thank you so much!
