### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by spiderwisp** [steveseguin/social_stream#35]
I'm not sure if this is the proper way to request a feature, but if you could make this work on Rumble it would be amazing!

**Comment by steveseguin** [comment]
Rumble is supported already.
:)
![image](https://user-images.githubusercontent.com/2575698/200020731-34d5bf6f-cd3d-4e54-909b-c6304b5a26f0.png)

**Comment by spiderwisp** [comment]
Sweet!
