### ISSUE TITLE
Feature Request - Ability to set custom Session ID

### ISSUE THREAD

**Issue by bronzegoddess** [steveseguin/social_stream#38]
Is it possible to set a custom session ID?

Right now I am testing this for use with Amazon Live, twitch, youtube and facebook. Since I am streaming on a Macbook air with limited resources, I run it on a different PC in my house and then use only the browser source in OBS. Having the ability to set a constant for stream id would be helpful in case the extension needs to be updated.  That way the stream overlays do not need to be replaced.

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/204120566-05895edd-4d72-4697-bbc7-b55f51d010c9.png)

**Comment by bronzegoddess** [comment]
Thank you!
