### ISSUE TITLE
Feature Request - Inject custom CSS / JS via Extension Pop up

### ISSUE THREAD

**Issue by bronzegoddess** [steveseguin/social_stream#39]
It might be useful to be able to add custom js / css via the extension popup options panel.  
Or the ability to use a url for js / css files which are automatically injected into the overlay page.

**Comment by steveseguin** [comment]
The dock.html and index.html pages do support custom js , css, and base64-css

code snippet:

````
if (urlParams.has('css')){
		var cssURL = urlParams.get('css');
		cssURL = decodeURI(cssURL);
		
		var cssStylesheet = document.createElement('link');
		cssStylesheet.rel = 'stylesheet';
		cssStylesheet.type = 'text/css';
		cssStylesheet.media = 'screen';
		cssStylesheet.href = cssURL;
		document.getElementsByTagName('head')[0].appendChild(cssStylesheet);
		
	}
	
	if (urlParams.has("base64css") || urlParams.has("b64css") || urlParams.has("cssbase64") || urlParams.has("cssb64")) {
		try {
			var base64Css = urlParams.get("base64css") || urlParams.get("b64css") || urlParams.get("cssbase64") || urlParams.get("cssb64");
			var css = decodeURIComponent(atob(base64Css)); // window.btoa(encodeURIComponent("#mainmenu{background-color: pink; ❤" ));
			var cssStyleSheet = document.createElement("style");
			cssStyleSheet.innerText = css;
			document.querySelector("head").appendChild(cssStyleSheet);
		} catch(e){console.error(e);}
	};
	
	...
	
	if (urlParams.has('js')){  // ie: &js=https%3A%2F%2Fvdo.ninja%2Fexamples%2Ftestjs.js
		console.warn("Third-party Javascript has been injected into the code. Security cannot be ensured.");
		var jsURL = urlParams.get('js');
		jsURL = decodeURI(jsURL);
		console.log(jsURL);
	```

If using OBS, it supports custom CSS already.

If I need to make this all easier to do, I can probably do that though.

**Comment by bronzegoddess** [comment]
Thank you. 
I am going the route of URL encoding a CSS file which is hosted.  It makes development a lot quicker for tweaking changes.  

I am a little confused on what is hosted on socialstream.ninja domain and what actually runs locally. 
I tried making edits to some of the html pages without any luck. ie (dock.html)

**Comment by steveseguin** [comment]
As per hosting, the links I provide for index and html and images are hosted online by default, but you can also run them locally.  Open the local files with your URL parameters added,

hosted online:  https://socialstream.ninja/dock.html?session=rqEt5aPK823412&nooutline
hosted locally:  file:///C:/Users/steve/Code/social_stream/dock.html?session=rqEt5aPK823412

Very important to make sure to add ?session=xxxxxx to the locally hosted file

If you are using a Mac system, OBS might force you to use the online version, as it doesn't seem to like running local files, but it should still work in the browser or on PC.

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/204134529-9d2dde8e-e143-4d61-a9d4-8143197f2dab.png)
