### ISSUE TITLE
Stopped working with MS Teams

### ISSUE THREAD

**Issue by GusBlanquel** [steveseguin/social_stream#40]
Before for this version, the social stream worked very well with Microsoft Teams in version web. 
With the new update it did'nt work.

**Comment by steveseguin** [comment]
Can you please check to ensure your session ID in OBS matches the session ID of the extension? 

You can just re-copy / paste a link from the extension's pop up menu also.


When updating the extension, depending on how you updated it, the session ID might have changed.

**Comment by steveseguin** [comment]
I gave teams a test and Microsoft had changed the name of one of the variables.

I updated the code to support their change;  every few months they seem to update their code that breaks things a bit.

Please download the newest version of the extension, reload it and teams, and please try again.

Thank you for reporting the issue.

**Comment by GusBlanquel** [comment]
Perfect!!! is working again werywell. Thanks you
