### ISSUE TITLE
Nimo.TV chat support

### ISSUE THREAD

**Issue by Balls0fSteel** [steveseguin/social_stream#44]
First of all, thank you for your beautiful piece of software. I wrote my own piece - but a lot of these stream sites require a sign-in which is simply put, quite troublesome. So if I could rely on a third-party project, it'd be much better than having to maintain my own solution.

What is NimoTV? 
"It's another game streaming platform." I'd say, if someone asked me at the bar.

Few things...
Registration: It asks for phone, but you can use Twitter, Google, Facebook as well. Honestly, not sure if you even have to register for this.
Chat URL: The chat URL is a numbered one, but it's fixed (unlike Youtube's silly changing ID).
It's just: `https://www.nimo.tv/popout/chat/069069069` with the user ID at the end. It stays ID-like even if user has a static channel name.

I tried to implement it myself but I saw in Twitch JS that you are making calls to your server for avatars and whatnot so that quickly make me give up. 

Thank you.

Ps.: Even login is quite impossible via Playwright and such because then you have to log into Twitter, then back, it gets real messy.

**Comment by steveseguin** [comment]
Thank you for the request. I'll take a look.

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/206239765-67c029f6-9d33-40b4-9e47-c7af2a2226ed.png)

added.

Avatar and donations aren't yet supported tho

**Comment by steveseguin** [comment]
I didn't test to see if it was working, but I thought I quickly added colors and badges. You need to enable it via the menu toggles though.

If it doesn't work, let me know
