### ISSUE TITLE
No funciona para whatsapp

### ISSUE THREAD

**Issue by luchoskay10** [steveseguin/social_stream#45]
ya actualice la extension y tambien puse F5 en whatsapp web y no funciona, en cambio en telegram funciona perfecto

**Comment by steveseguin** [comment]
I'll take a look. thank you

**Comment by steveseguin** [comment]
download the newest version and let me know if it works after a reload. ty

**Comment by luchoskay10** [comment]
perfecto, todo bien! muchas gracas, excelente trabajo
