### ISSUE TITLE
Colors for users

### ISSUE THREAD

**Issue by Balls0fSteel** [steveseguin/social_stream#46]
Okay so I tried to comment here and I was like meh I'll type it out: https://github.com/steveseguin/social_stream/issues/44

**This is real simple**, don't panic! I noticed people don't have names, making reading a bit difficult at times.

- Have a block of available, readable colors or generate them on the fly. If you can't find find a block of readable colors, color values, you can copy-paste some solution from SO, like this one: https://stackoverflow.com/questions/12043187/how-to-check-if-hex-color-is-too-black

- I would give users a unique color BASED ON NAME. IF a name does not have a color yet, we get them one from our color array. When that happens, we assign a color to this name. Kinda like a key:value lookup. Easy.

- I would not really worry about giving people all sorts of colors, like they should be so different and whatnot. Too much effort. Even with just random luck, you should end up with only a few names having similar colors. I mean yeah you could maybe come up with a method, like "color similarity" but eh, sounds like an effort to me, which is not my favorite. Also with more than a few people, you'd definitely end up with similar colors IMO.

Feel free to close this one by the way! And I swear I won't dump 100 tickets in your Issue Tracker either.

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/209025442-eeee6a64-e5a8-46fe-a2d7-ab6b4852f138.png)

![image](https://user-images.githubusercontent.com/2575698/209025473-33b69271-8360-425d-8a49-108e955f4ce2.png)


I've added this feature.  To avoid having to store names in a key store, I just went with a predictable and simple `string -> number -> color` conversion function.  A key store works also, and I may add one in is caching is needed for performance reasons.

It probably could use some polish, so feedback welcomed
