### ISSUE TITLE
SocialStream just kinda stopped working? No clue why?

### ISSUE THREAD

**Issue by Balls0fSteel** [steveseguin/social_stream#47]
I know this is vague and I checked the FAQ section but it just stopped working?

Is there a way to see what might cause this? I saw a new update, I did that, but no dice. The used key / URL is 100% correct, I tried the listed steps. But nothing.

Where should I look?
 
Thank you.
Ps.: I realize how much devs hate vague reports but I really tried looking everywhere and could not come up with anything.

**Comment by steveseguin** [comment]
Hey , did you figure this out?

If you reload the extension, you'll need to reload the chat sources as well, such as Twitch pop out, etc.  

When it stopped working, did you change any networking settings? VPNs ?

**Comment by zafulz** [comment]
Did the same thing, YT is working now, but not Twitch. All tbs steps were taken into account and my browser is pretty much restarded without cache nor cookies.

**Comment by steveseguin** [comment]
I've fixed support for Twitch now-- they rolled out an update that broke my code.

I'll continue to test YT and Twitch and push more patches as needed.

Thank you for reporting the issues
