### ISSUE TITLE
LinkedIn live chat integration

### ISSUE THREAD

**Issue by cchaudier** [steveseguin/social_stream#5]
Hey @steveseguin

Thanks for all you amazing and powerfool tools.

Can you add LinkedIn Live chat?

**Comment by steveseguin** [comment]
I've got a few to add.  I'll add linkedin to the list.  thank you for the request

**Comment by steveseguin** [comment]
added support. at least, guest-view Linkedin events comment support was added.  I haven't been able to find live streams to test with, and I dont have access to publish my own live streams currently, so I'm working a bit blind here.

Not sure if images work.  replies don't work I think.    If things don't work in your testing, i'll need someone to host a live stream for me for an hour to test against.
