### ISSUE TITLE
Enable text-to-speech for New members

### ISSUE THREAD

**Issue by diegoveloper** [steveseguin/social_stream#52]
hello, there is a text-to-speech option for Donations only, is there any config that we can use to enable the TTS for New members too? Like this

![welcome_developer](https://user-images.githubusercontent.com/4898256/211989758-62c5c1f3-7ac6-4afa-80e8-0ca34ce4ea2b.png)

And if we can have the autoselection also for the new members (like we have for donations), that would be great! :D

**Comment by steveseguin** [comment]
There's an auto highlight mode for donations only.

"When auto-selecting is on, only auto-select donations".  If you use this and the tts mode, you should be able to have donations read out that way automatically.

I'm not sure about new members; I probably could add that in if not.

**Comment by diegoveloper** [comment]
Yeah, auto highlight for donations only works perfect, but not for new
members.

**Comment by diegoveloper** [comment]
Any chance on this? :D

**Comment by steveseguin** [comment]
Added it, but I haven't had time to test it yet.

![image](https://github.com/steveseguin/social_stream/assets/2575698/559ad577-7904-45c2-99be-f5a609928282)

or &ttsnewmembers , added to the featured.html page

**Comment by diegoveloper** [comment]
hello, I tried using `&ttsnewmembers` on this url 

`https://socialstream.ninja/featured.html?session=bn86sa4We3&showtime=40000&voice=jorge&tts=es-ES&latency=0&pitch=0.4`

so it was 

`https://socialstream.ninja/featured.html?session=bn86sa4We3&showtime=40000&voice=jorge&tts=es-ES&latency=0&pitch=0.4&ttsnewmembers` 

but then when a new super chat came, the voice didn't play :(

**Comment by steveseguin** [comment]
Is a super chat the same as a new member?  I think super chat counts as a donation, so you'll need to add `&ttsdonos` as well.  One to read out new members, and one to tell the system to read out donations.

**Comment by diegoveloper** [comment]
ok, I see, when I have this :

```
https://socialstream.ninja/featured.html?session=bn86sa4We3&showtime=40000&voice=jorge&tts=es-ES&latency=0&pitch=0.4
```
I can see the featured message with voice/sound (with donations or message that I selected from the dock, which is what I need).

when I add any of these or both `&ttsdonos&ttsnewmembers` , the featured message stop playing sounds when i select the message from dock if it doesn't have donation but it works with message with donation.

Any chance to do :

- show / play sound any message that I selected from the dock and is displayed in featured message?
- show automatically the donation message with voice (I think this is working).
- show a featured message of a new member with voice (I didn't test this but I suppose ttsnewmembers should work)

**Comment by diegoveloper** [comment]
hi @steveseguin , do you know what's the event/method (and in which file is that) when user TAP a message on the dock?

**Comment by steveseguin** [comment]
`selectedMessage(false, ELEMENT)` ?

**Comment by diegoveloper** [comment]
I added an `else` condition here:  https://github.com/steveseguin/social_stream/blob/main/featured.html#L2389C5-L2404C10

Like this: 

```
else if(msgPlain) {
		speak(chatname + "! ! .. " + msgPlain);
}
```

I also added some console logs and it's going there, but the bot is not talking, do you know what could be the reason? 

This s the log

```
You can do &voice=VOICENAME to try to force select a voice based on a partial string match of its name.
featured.html?session=bn86sa4We3&showtime=40000&voice=jorge&tts=es-ES&latency=0&pitch=0.4&ttsdonos&ttsnewmembers:1634 (179) [SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, …]
featured.html?session=bn86sa4We3&showtime=40000&voice=jorge&tts=es-ES&latency=0&pitch=0.4&ttsdonos&ttsnewmembers:1655 Voice being used:
featured.html?session=bn86sa4We3&showtime=40000&voice=jorge&tts=es-ES&latency=0&pitch=0.4&ttsdonos&ttsnewmembers:1656 SpeechSynthesisVoice {voiceURI: 'Jorge (Spanish (Spain))', name: 'Jorge (Spanish (Spain))', lang: 'es-ES', localService: true, default: false}
``` 

I just want the bot talk when:

- there is a new donation (automatically)
- there is a new member (automatically)
- when I select a message from the dock

can you help me?

**Comment by steveseguin** [comment]
Where do you want the voice to come from; the featured.html page or the dock.html page?

For example, you can right-click a message in the dock and hit "text to speech", and I believe it should play.  

By adding &ttsdonos &ttsnewmembers, those specifically tell the featured page not to play audio UNLESS its one of those.  Whether you manually select it or automatically select it from the dock, it has no idea.  No data is being passed from the dock to the featured chat page that you've manually selected it vs it being automatically selected.

To solve this, we need to include some meta data with the message object we are sending to the featured chat page, and then add logic to the speech logic to make an exception for messages of that marking.

**Comment by steveseguin** [comment]
![image](https://github.com/user-attachments/assets/be88ac43-0827-4a75-aa60-9ffd2d2f0492)

**Comment by diegoveloper** [comment]
perfect, thank you so much! 

just for the record, this is the URL : https://socialstream.ninja/featured.html?session=[session_id]&showtime=40000&voice=jorge&tts=es-ES&latency=0&pitch=0.4&ttsdonos&ttsnewmembers&ttsclicked
