### ISSUE TITLE
When sending message from Menu Bar to YT chat, error avatar pops up on live feed overlay

### ISSUE THREAD

**Issue by Darmorque** [steveseguin/social_stream#61]
I use OBS 29.0.2 + latest Social Stream overlay. Whenever I send a message to Youtube chat using Social Stream's built in Menu Bar, the message properly appears in chat, but at the same time the overlay displays empty avatar by itself and it just stays there. No name, no message, just the placeholder avatar image and that's all. To be precise - it pops up by itself upon hitting enter to send the message, without pinning anything from chat. Actually, pinning any comment is the only way to replace it and therefore remove it from screen.

I tried clean OBS install, different chromium-based browsers, including clean Chrome install, and in every case the issue was the same. I looked a bit into browser's Inspect Element tool, and clearly 'errorimage' function was there while the empty avatar was displayed, but as I'm by far not very familiar with the code, I can't tell whether it's a valuable hint or completely not.

**Comment by steveseguin** [comment]
Thank you for reporting the issue again.
