### ISSUE TITLE
Rokfin not showing up

### ISSUE THREAD

**Issue by wdearman** [steveseguin/social_stream#64]
Hello again. I appreciate your quick response yesterday (Mon 2/6/23) to adding Rokfin to the list of platforms. But I am still not seeing it show up with live chat. I tested out (so far) YouTube, Twitch and Rumble and all work fine. I downloaded the latest version from here this morning to make sure I was 100% up to date. 
On Rokfin, I popped out the chat as a separate window and, on a different test, I tried it as a pop out but in a tab (YouTube, Twitch and Rumble chats in tabs worked fine). I was wondering if I was doing something wrong or missing a step. Again, thank you so much for adding Rokfin and I appreciate any and all help on this. It really looks great by the way. And thank you in advance.

**Comment by steveseguin** [comment]
I joined a Rokfin live stream as a viewer, not a publisher.  That might be the difference.  If you have a live stream setup and provide the link, I can test against it specifically.

**Comment by wdearman** [comment]
Do you want me to set up a test stream on my Rokfin channel and send you the link while it's live?

**Comment by steveseguin** [comment]
I'm available at the moment to test and verify with you, if you do

**Comment by wdearman** [comment]
Okay cool. Stand by and I'll set it up. And thanks you for helping with this.

**Comment by wdearman** [comment]
Did you want the live link? https://rokfin.com/stream/29664

**Comment by steveseguin** [comment]
The chat stopped working entirely for me after a couple page refreshes.
 Hrm.
 
 There were some differences between your chat and the chat I had tested with earlier though

**Comment by wdearman** [comment]
Okay. So what happens next?

**Comment by wdearman** [comment]
Did you want me to kill the stream or keep it going?

**Comment by steveseguin** [comment]
it's working again.  I need just a bit of time to figure out what's breaking; found a couple so far.

keep it going for a bit longer ;)

**Comment by wdearman** [comment]
No problem. As long as you need brother.

**Comment by steveseguin** [comment]
Can you download the newest extension, replace the old files, reload the extension, and then reload the pop out chat?

ie: https://rokfin.com/popout/chat/121619?stream=29664

**Comment by wdearman** [comment]
Okay. Hang on.

**Comment by wdearman** [comment]
Is the extension the same download link as usual?

**Comment by steveseguin** [comment]
Ya.  

If you use git, you can just do git pull. otherwise, just download the zip file

**Comment by steveseguin** [comment]
https://github.com/steveseguin/social_stream/archive/refs/heads/main.zip

**Comment by wdearman** [comment]
Okay, had to start another stream because the new chat was on another scene selection. https://rokfin.com/popout/chat/121624?stream=29668 But so far it's working!

**Comment by wdearman** [comment]
Steve I think think we have, as the kids say, a winner winner chicken dinner. Thanks man I really appreciate you. As soon as I get some cash I'll float some your way. You went above and beyond and I know this will help Rokfin creators greatly!

**Comment by steveseguin** [comment]
I appreciate the request. Here to help, big or small; I know how frustrating it is that only the most mainstream sites and services are supported.

Anyways, have a great one. Thank you for hosting a test stream for me

**Comment by wdearman** [comment]
no problem! Have a great day!
