### ISSUE TITLE
Slido

### ISSUE THREAD

**Issue by Ant-Productions** [steveseguin/social_stream#65]
Hi Guys, the project looks great, is there any chance you could add Slido, https://app.sli.do, as I would love to be able to pull the data form gigs we do. Thanks

**Comment by steveseguin** [comment]
Thank you.

I've added support for the Q&A section.  I think it should work with this page, where XXXXX is replaced as needed. https://app.sli.do/event/XXXXXXXXXXXXXXX/live/questions
