### ISSUE TITLE
Mobcrush support

### ISSUE THREAD

**Issue by ASchneiderBR** [steveseguin/social_stream#7]
Hello Steve!

Sorry to bother you, again :)

Do you think Mobcrush could work here as well? Mobcrush is an amazing free service, way better compared to the free tier from Restream, since you can live stream to a Facebook page and also send to a custom RTMP.

Thank you very much 👍

**Comment by steveseguin** [comment]
Added basic support for mobcrush 
should work with this page:

https://studio.mobcrush.com/chatpopup.html

Took some time, as it was more complicate to get working than with some other sites.

**Comment by ASchneiderBR** [comment]
Thank you very much Steve!
