### ISSUE TITLE
twitch/7tv emotes not showing

### ISSUE THREAD

**Issue by Zelduh** [steveseguin/social_stream#80]
![Screenshot 2023-02-27 112453](https://user-images.githubusercontent.com/126505459/221636483-a087d348-2ba6-4893-9352-3caf563336ca.png)

i only have 7tv/bttv extensions installed for chrome, and im also using the latest update. 2/27/23

**Comment by steveseguin** [comment]
I'm really not sure what to say, as it works fine for me
![image](https://user-images.githubusercontent.com/2575698/222557441-c23c0092-eae6-4f54-b7e4-dc202e343805.png)

Are you using special settings in BTTV/7TV?  

I pushed an update to double check things, but I may need more help debugging the issue if it persists.  maybe right-click an emoji in the twitch chat, inspect the element, and share a screen shot of it here? The code might tell me something

**Comment by Zelduh** [comment]
yes sry it took so long to get back to you, but i'v fixed the issue by going into extensions within Chrome and clicking "Load unpacked" again and starting over from there with an updated version of the "social_stream-main" file. Not sure why it didn't work/stopped working the first time, but maybe it was something on my end. 

screenshot is what i re-did as another example
![Screenshot 2023-03-06 125036](https://user-images.githubusercontent.com/126505459/223204300-cd9163b2-2686-4822-b77e-7fa07026f200.png)

**Comment by Zelduh** [comment]
working as preview in OBS
![Screenshot 2023-03-06 125707](https://user-images.githubusercontent.com/126505459/223204803-210b4b5d-cdcc-4415-974f-363b53a3e811.png)
