### ISSUE TITLE
DLive not functional.

### ISSUE THREAD

**Issue by filcard** [steveseguin/social_stream#90]
Just an FYI that DLive doesn't seem to work, or if it does, it is sporadic. I haven't successfully had it work in all my tries. Perhaps you are unaware, but they redid their site a few months ago, bringing back the chest. What this means is that the popout chat has a random string of characters in the url, and the chat can't be popped out until after the stream has started. The random string is different for each stream, I believe.

I multi-stream on 5 platforms, and all the others work like a charm! Great work on this plugin.

**Comment by steveseguin** [comment]
I wasn't able to reproduce any problem with Dlive, but I added some code to try to "keep alive" the chat if the pop out chat gets minimized.

https://github.com/steveseguin/social_stream/commit/f2c40edc41fd8847df29f91db539518e74a3b0e9#diff-8f88c0451d68e9466cdd0e090f5bc41d6d35cfb2f7413d9158087d102123a13f

I've also added the option to auto pop out dlive to the menu; from quickly testing, that random code doesn't matter much?   Anyways, if you find it works or doesn't work for you, let me know:

![image](https://user-images.githubusercontent.com/2575698/227803268-4fe94d15-a14e-4146-88b0-1ded22648ca2.png)

**Comment by filcard** [comment]
Oh weird. Thanks for looking into it. I'll try again later today. Not sure why DLive never works for me.

**Comment by steveseguin** [comment]
If you have any extensions installed that modify the chat, or some non-default settings for the chat, let me know and I'll test with those too
