### ISSUE TITLE
Inquiring About striphtml and stripemoji 

### ISSUE THREAD

**Issue by as2648as** [steveseguin/social_stream#93]
Hello, I would like to inquire about the parameters `&striphtml` and `&stripemoji`.

1. I believe the functionality of `&striphtml` and `&stripemoji` is to help users remove any HTML and emoji from chat messages.
Is my understanding correct?
The current test results do not seem to support this idea.
As shown in the image below, the Twitch popout is what I would expect, but the `dock.html` is what is currently being displayed.
![image](https://user-images.githubusercontent.com/27887647/230733060-eb66d1c8-404f-4385-aab2-b036b44b1fca.png)

2. Building on the previous question, I observed in the developer tools that the message retrieval in `twitch.js` seems to include html elements, which can affect the functionality of `stripHtmlFunction` when `&striphtml` is enabled but `&stripemoji` is not.
This is because `stripHtmlFunction` removes html elements, but Twitch and Youtube's emojis are presented using `<img>`.
![image](https://user-images.githubusercontent.com/27887647/230731447-73e706df-60ac-4d74-8be1-2358b556c3b2.png)

3. We can use [this post](https://stackoverflow.com/questions/18862256/how-to-detect-emoji-using-javascript) for the `stripemoji` parameter and add code to check for `<img>` elements to more accurately replace emoji elements.

**Comment by steveseguin** [comment]
Using the following in Twitch /w BTTV: ```asdfasdfasd❤️‍🔥 sdfgsdfg :(  gdsfgsdfg```

stripemoji + striphtml:  ![image](https://user-images.githubusercontent.com/2575698/230740990-e2eca98d-b6d1-4bc9-bb45-edf8601a6d0e.png)

stripemoji:  ![image](https://user-images.githubusercontent.com/2575698/230741003-aa4ed145-df0d-462f-b4e3-4bfbd36e7de4.png)

striphtml ![image](https://user-images.githubusercontent.com/2575698/230741034-f074641d-a20e-4f8c-b8d1-ecbb3dcfb54d.png)

nothing added: 
![image](https://user-images.githubusercontent.com/2575698/230741054-b7787f23-66c2-494b-84ef-e8d1b30600f8.png)


The unhappy face is replaced by an Image by BTTV, and that gets removed with using &striphtml.  I do not know if an image is an emoji or something else.

An emoji when using &stripemoji is a non-alphanumeric unicode character, representing an image, but not HTML. -- it's just text.  Some fonts render emojis right; some don't.  

To get rid of both images and text-based emojis, you'd need to use striphtml + stripemoji.  It seems to work in my testing.  

I'm open to considering treating all images as emojis, but I don't assume that in this case.

**Comment by as2648as** [comment]
Okay, I misunderstood the purpose of these features at first.  
Perhaps in the future, I will add or modify some text processing features in a new branch, such as:  

 * Only remove emoticons using the `<img>` element  
> This allows text to include elements such as underline, strikethrough, blue URLs, etc.  

 * Remove Unicode emojis  
> Such as expressions 😊, symbols 🎶, items 🚗, etc.  

 * Remove URLs  
> 1. When TTS is enabled, reading out URLs may cause trouble. Another solution is to add additional checks in TTS.  
> 2. URLs are just too long.

The reason I want to make these improvements is that some people may not want many graphics in the chat room after using emote.html.  
In addition, having more options means users can choose what they need more flexibly.
Looking forward to your reply.

By the way, as far as I know, "emoji", "emoticon", and "emotes" have different meanings in English.  
Perhaps my choice of words may cause confusion, sorry about that.

**Comment by as2648as** [comment]
@steveseguin I've implemented the features mentioned in the [latest comment](https://github.com/steveseguin/social_stream/issues/93#issuecomment-1502161341) and written some code for it.
Since it's easier to test on custom.js and these features may not be merged into the main branch,
I'm sharing my code [here](https://gist.github.com/as2648as/4c8b1f7101a961c30a3fe4dc543043e5#file-custom-js) in hopes that it might inspire you with some ideas.

**Comment by steveseguin** [comment]
Thank you, kindly. I'll dig into it
