### ISSUE TITLE
Twitch Name Colors

### ISSUE THREAD

**Issue by kidnotkin** [steveseguin/social_stream#98]
Twitch chat names don't appear to show up. I know it's possible to randomize the colors if they aren't available, but is there a way we can actually get the original name colors?

**Comment by steveseguin** [comment]
I think there was a glitch in the name colors for Twitch; it should be fixed if you update the extension again.  

"Twitch chat names don't appear to show up." - the names aren't showing up? I assume this is a typo, but just in case I tested and with all the major Twitch extensions (and without), the names appear working.

If you do update the extension (download, replace files, reload), you'll need to also then reload the twitch pop out chat after.

Thank you for reporting the issue.

**Comment by kidnotkin** [comment]
Yes, it was a typo. I was only talking about the chat name *colors* 
After updating it appears that twitch chat does not update unless the tab for twitch chat is open and visible on screen. This isn't the case for other chats, however.
