### ISSUE TITLE
Low Resolution Twitch Badges

### ISSUE THREAD

**Issue by chodelay** [steveseguin/social_stream#99]
Badges for twitch users are rendered in the lowest resolution. I had a look at twitch.js - on line 113, it grabs the **first** in the img srcset for each badge. This means it grabs the 18x18 version, where there are 36x36 and 72x72 versions available.

Are you able to update this to grab the last element in the srcset instead?

Excellent work by the way. Love it.

**Comment by steveseguin** [comment]
I updated it.

My concern is that I only render 20x20 normally, and 72x72 will hurt system performance without much benefit.

![image](https://user-images.githubusercontent.com/2575698/232238680-07172ff6-3f6e-4f59-9b18-77f47ff492a8.png)

**Comment by chodelay** [comment]
Forgot to say thanks the other day. Thanks!!
